### ISSUE TITLE
UKIS: None options are getting preselected.

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1013]
### Expected behaviour
'None' options must not get pre-selected.

### Actual behaviour
All the none options are getting pre-selected

### Steps to reproduce the behaviour
Launch an UKIS survey.
Navigate to Question 9.9 
### Screenshot
<img width="707" alt="screen shot 2017-03-06 at 18 23 13" src="https://cloud.githubusercontent.com/assets/21335236/23623486/2087d1ec-029a-11e7-85b1-dbe5237a5985.png">

**Comment by collisdigital** [comment]
I think this was introduced by https://github.com/ONSdigital/eq-survey-runner/pull/994

**Comment by collisdigital** [comment]
Something to do with `app/templates/partials/widgets/multiple_choice_widget.html` and using `None` as the value, the previous version of this file specifically checked for the string `'None'` but now doesn't although reverting back to that changes the problem to not display the user's selection was 'None'

**Comment by collisdigital** [comment]
Actually checking `tags/v2.0.0` it doesn't restore the radio value if 'None' is selected.

**Comment by collisdigital** [comment]
Checking the radio `value` in the schema to something else e.g. `_None` works-around the issue but that probably affects downstream processing so needs a proper fix.
