### ISSUE TITLE
Failed requests for URLs containing <no source>

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#1053]
### Expected behaviour
No requests for URLs containing `<no source>`

### Actual behaviour
Logs show failed requests to `/s/css/census/themes/census/<no%20source>`

### Steps to reproduce the behaviour
Unknown, these errors are from the server logs

**Comment by collisdigital** [comment]
Also blocked by the WAF as a XSS pattern
