### ISSUE TITLE
S-5 - 1st Page - Reporting Unit Reference display

### ISSUE THREAD

**Issue by stevevic** [ONSdigital/eq-survey-runner#106]
Please display Ru-ref without checkletter (it is needed with the checkletter when sending downstream0

**Comment by stevevic** [comment]
[https://trello.com/c/zbWNOwY4/43-eq-43-basic-business-landing-page-3-pts](url)

**Comment by warrenbailey** [comment]
Steve I don't think we should be altering this data, this is pass through data to the SDX team??

Also I thought the RRM team were told to append the check letter? If we are then meant to separate it back out, what was the point of appending it in the first place?

**Comment by stevevic** [comment]
Not requiring to separate out the check letter, but preferable not to display it if that's possible.  Respondent ID full reference, including checking letter, is needed for downstream processing (which drove our request for concatenating)

**Comment by warrenbailey** [comment]
It feels like a hack, if we needed the data in its separate parts, even if it's only for display purposes, it should be passed through separately and then combined by the SDX team for downstream systems. 

Is this MCI specific or for all surveys?

**Comment by collisdigital** [comment]
Not showing it is the same as separating it, we need to code in something that understands the structure of the data being supplied and manipulate it; if we do do this for MCI it needs addressing (along with the other debts) straight afterwards. Concatenation and splitting strings like this between systems is poor data architecture and must be avoided.

**Comment by stevevic** [comment]
Will investigate impact of displaying with the checkletter (when calling Respondents are asked to key in their reference number) and advise.  No change for now.

**Comment by collisdigital** [comment]
Thanks Steve

**Comment by hamishtaplin** [comment]
I'll close this then, re-open if it becomes an issue again.

**Comment by stevevic** [comment]
Agreed - have confirmed with Business that it is usual to ask caller for Respondent ID even if they enter it.  To be monitored.
