### ISSUE TITLE
UKIS: Clicking on 'General Business Information' navigation link navigates to Landing page

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1079]
### Expected behaviour
Must navigate to 'General Business Information' section

### Actual behaviour
Navigating to Landing page.

### Steps to reproduce the behaviour
launch UKIS survey
Answer few sections and
click on 'General Business Information' navigation link
### Screenshot
<img width="1116" alt="screen shot 2017-04-03 at 11 47 29" src="https://cloud.githubusercontent.com/assets/21335236/24606127/975d1e9c-1863-11e7-8f6f-9d49e85fda0b.png">

**Comment by collisdigital** [comment]
won't fix as this will causes undesirable behaviour for UKIS respondents (see #1082)
