### ISSUE TITLE
White text rendering too heavy in Firefox

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1103]
### Expected behaviour

That the font weight / anti-aliasing is consistent - preferably have Firefox using Chrome's rendering weight. This is only notable where text is white on colour.

### Actual behaviour

Firefox is rendering reversed text more heavily than Chrome. (Firefox top vs Chrome below)
Note '**BETA**' and '**Monthly**' and '**Notice is given...**' which are heavier in the Firefox rendering

![ons-screenshot-0215-header-font-rendering-21042017](https://cloud.githubusercontent.com/assets/22910336/25285173/3c33ad2c-26b1-11e7-9dc8-6e6f1b45600b.png)

### Steps to reproduce the behaviour

Preview in Firefox and Chrome

#### Browser

Chrome - 57.0.2987.133
Firefox - 52.0.2 (64-bit)

#### Operating System

Macintosh OS X 10.12.4

**Comment by nealedj** [comment]
@armstrongb Do you know if this has been looked at?

**Comment by benhowes** [comment]
![screen shot 2018-08-08 at 11 25 07](https://user-images.githubusercontent.com/471170/43832005-e556a366-9afd-11e8-8901-b79bbda97250.png)

Safari Left, Firefox Right.

This appears to still be an issue, might be worth fixing as part of #1710 @boxadesign?
