### ISSUE TITLE
Print Preview: Radio button and Check box display issue 

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1122]
### Expected behaviour
On the print preview the selected Check boxes and Radio fields must be displayed clearly.

### Actual behaviour
 Check boxes and Radio fields are not displayed as expected in Google chrome. (PFA)

###Note: In IE the print preview works as expected for both checkboxes and radio fields. 
#### Browser
Google Chrome
### Screenshot
![radio button](https://cloud.githubusercontent.com/assets/21335236/25743384/024412ec-318c-11e7-87f4-017ddc7bba59.png)

**Comment by bennpearson** [comment]
@yoganandkunche I can't recreate this in chrome.
