### ISSUE TITLE
Review project dependencies in light of BitHound analysis.

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-survey-runner#1132]
### Description
The [BitHound Analysis for survey runner](https://www.bithound.io/github/ONSdigital/eq-survey-runner/https://www.bithound.io/github/ONSdigital/eq-survey-runner/) has highlighted a number of out-of-date packages being used in survey runner.
A few of these packages are considered insecure and have security advisories against them.
Others are listed as risky upgrades since the versions have fallen behind quite a bit.
Granted some of these are dev dependencies, and not application dependencies. But probably still worth reviewing at some point.

I've created this task so that the front end dependencies can be reviewed and a decision taken as to whether we:
a) Leave the versions as-is accepting the risks and potentially more difficult migrations in the future,
b) Upgrade the dependency versions to newer releases, or
c) use a different dependency.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/4097796/26063363/befd89a8-3985-11e7-87b7-da993915352f.png)

**Comment by nealedj** [comment]
Updated analysis:

<img width="941" alt="screen shot 2018-04-03 at 15 45 27" src="https://user-images.githubusercontent.com/356075/38256403-15e2055e-3756-11e8-9430-5ab869ff9179.png">

**Comment by MebinAbraham** [comment]
Reopening as it turns out, there are more issues that needs addressing but were missed accidentally. A future card will address the rest.
https://www.bithound.io/github/ONSdigital/eq-survey-runner/master/dependencies/npm#filter-priority-dep
