### ISSUE TITLE
SDX date format has been removed

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/eq-survey-runner#1146]
The string formatting for sdx date values has been removed in https://github.com/ONSdigital/eq-survey-runner/commit/0af09a85d195ccc672377df59add086f09f6a803#diff-cb8b13ea27d26f0e53eb65167566c085L107

This could cause potential issues downstream; would it be possible to add it back in?

**Comment by jonnyshaw89** [comment]
@JamesGardiner That piece of code was removed because the code wasn't hitting it.
So removing this code should have had no chance to what we send downstream.
Have you noticed a change in what is being sent?

**Comment by JamesGardiner** [comment]
https://github.com/ONSdigital/eq-survey-runner/commit/0af09a85d195ccc672377df59add086f09f6a803#diff-344744166e99e765c05d50b0dd2ad79fL197

**Comment by JamesGardiner** [comment]
I think @warrenbailey noticed a difference this week

**Comment by jonnyshaw89** [comment]
@JamesGardiner by not being used i meant that the code couldn't be hit rather that it wasn't in the code. As we changed the way we store answers this statement could never be true `isinstance(value, datetime)`

**Comment by collisdigital** [comment]
@JamesGardiner can we close this?

**Comment by JamesGardiner** [comment]
@collisdigital yes.
