### ISSUE TITLE
Squared units consitency

### ISSUE THREAD

**Issue by bennpearson** [ONSdigital/eq-survey-runner#1239]
### Expected behaviour
Consistent use of squared units

### Actual behaviour
Square Miles is abbreviated to `sq mi` when other units such at square kilometres use `km²`

![screen shot 2017-09-14 at 10 25 31](https://user-images.githubusercontent.com/130312/30422188-1784701c-9937-11e7-8cb4-d2149994573e.png)

**Comment by nealedj** [comment]
Closing this off for now as it isn't clear whether it's a requirement or not. Will revisit if a requirement manifests itself.
