### ISSUE TITLE
Clicking on Date Range error messages does not focus date input

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1241]
### Expected behaviour
When I click on the error message then the first date input box should be focused

### Actual behaviour
Nothing is focused

### Steps to reproduce the behaviour
Enter a from data after the to date

### Screenshot
![screen shot 2017-09-14 at 13 42 11](https://user-images.githubusercontent.com/7594012/30430325-c1ad0bba-9952-11e7-95df-4d348fdd07ed.png)

**Comment by collisdigital** [comment]
Can we add a test to verify this behaviour going forwards please.
