### ISSUE TITLE
MWSS allows respondent to submit even when a mandatory question is not answered

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1251]
### Expected behaviour
Must not navigate to Summary page as there is an uncompleted Mandatory question under 'Pay Patterns group.

### Actual behaviour
Navigate to summary and allows respondent to submit the questionnaire. Also displays the mandatory question as No answer provided. (PFA)

### Steps to reproduce the behaviour
Launch MWSS survey
select Weekly and click save and continue
select 'No, I need to update the patterns' and click save and continue
Observe the 'Pay patterns' gets a green tick (which is not correct as the section is not complete yet)
click on Weekly from the navigation
continue to complete the questions and reach Summary page.

### Screenshot
<img width="693" alt="screen shot 2017-09-19 at 14 15 49" src="https://user-images.githubusercontent.com/21335236/30594181-120dfb64-9d45-11e7-93f0-2c13adf63ffc.png">

**Comment by nealedj** [comment]
@yoganandkunche do you recall if this is still an issue?

**Comment by nealedj** [comment]
It's worth mentioning that section completeness is getting a bit of an overhaul and that may fix this issue. Leaving open to revisit and verify later.
