### ISSUE TITLE
Errors refer to non-existent phone number

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#1253]
### Expected behaviour
Error messages refer respondent to contact information

### Actual behaviour
Error message refers to phone number that has been removed

### Steps to reproduce the behaviour
- Trigger an error (e.g. go to a non-existent URL)

#### Browser
- all

#### Operating System
- all

### Screenshot
![image](https://user-images.githubusercontent.com/14041600/30649922-75ded346-9e19-11e7-94b6-423843dc02cd.png)

**Comment by ajmaddaford** [comment]
Fixed in https://github.com/ONSdigital/eq-survey-runner/pull/1257
