### ISSUE TITLE
Welsh language not working

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#1263]
### Expected behaviour
Launch with language 'cy' for census household and see Welsh language variant.

### Actual behaviour
Falls back to English

### Steps to reproduce the behaviour
- Launch census_household with language set to 'cy'
- See English variant.

### Screenshot
![image](https://user-images.githubusercontent.com/14041600/30818848-a8b13454-a214-11e7-84d0-bec7f819f5f3.png)

![image](https://user-images.githubusercontent.com/14041600/30818834-9da18bf4-a214-11e7-9d66-2c4eee67127e.png)

**Comment by jcox-dev** [comment]
I can only see an "en" directory inside "[data](https://github.com/ONSdigital/eq-survey-runner/tree/master/data)", which is where the runner [checks](https://github.com/ONSdigital/eq-survey-runner/blob/553daa0a1e4c980a85f397da84528c6b7b183ef5/app/utilities/schema.py#L28) by default for the translated schemas. 

Are we missing files in the repo?

**Comment by shahi645** [comment]
Once https://github.com/ONSdigital/eq-translations/pull/13, is merged to master and tagged we can update `translate_schemas.sh` in SR and this issue should be fixed.

**Comment by shahi645** [comment]
the above PR is merged so this issue is solved
