### ISSUE TITLE
JS Feedback does not grey out all the fields during session timeout pop up.

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1280]
### Expected behaviour
Must grey out the whole page like it does on the survey page

### Actual behaviour
Feedback tab is not greying out all the fields.

### Steps to reproduce the behaviour

Launch test_timeout.json
click on help us improve link
which opens the feedback in the current page 
allow to time out

**Comment by jcox-dev** [comment]
Linked to #1246
