### ISSUE TITLE
Generated requirements.txt contains test dependencies

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1324]
### Expected behaviour
The dev dependencies should not in included in the requirements.txt when the app is deployed

### Actual behaviour
The test dependencies are in the requirements.txt

### Steps to reproduce the behaviour
`pipenv lock -r > requirements.txt`

**Comment by jcox-dev** [comment]
This seems to be intended behaviour. See: https://github.com/kennethreitz/pipenv/issues/245.

We could use this script as a workaround (from the above): https://github.com/kennethreitz/pipenv/issues/245#issuecomment-283694215

~Or something like: https://github.com/UnitedIncome/serverless-python-requirements/issues/87#issuecomment-335454523~ (pip freeze does not hash requirements).

**Comment by jcox-dev** [comment]
Fixed in latest version of Pipenv: kennethreitz/pipenv#972

Upgrading Pipenv on Jenkins would solve this issue.
