### ISSUE TITLE
Census household: Section shows as complete when routing change wipes already answered question

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1334]
### Expected behaviour
Must either remove the green tick or must not wipe the answers (PO to Confirm)

### Actual behaviour
Wipes the household people and retains the green tick then there are unanswered questions

### Steps to reproduce the behaviour
Launch census_household survey
complete who lives here section by adding 2 people (make sure the section gets a green tick)
Navigate back to the 1 question in 'who lives here section'
select 'no'
click save and continue (make sure the green tick is removed)
click previous
select 'yes' and save and continue

### Screenshot
<img width="1069" alt="screen shot 2017-11-03 at 14 26 47" src="https://user-images.githubusercontent.com/21335236/32379331-262b3afc-c0a5-11e7-8531-50a6f994d77d.png">

**Comment by nealedj** [comment]
Fixed
