### ISSUE TITLE
Plurality of error messages

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#1377]
### Expected behaviour
When there is only one error message, it should be worded appropriately, something like:
- This page has an error
- This must be corrected to continue

### Actual behaviour
When only one error is raised the wording is:
- This page has 1 errors 
- These must be corrected to continue

### Steps to reproduce the behaviour
On any screen that can generate an error, input invalid data and submit.

### Screenshot
![image](https://user-images.githubusercontent.com/1754822/33064650-5a8c2796-ce9e-11e7-8e25-3c455cfa1567.png)

**Comment by shahi645** [comment]
@ajmaddaford maybe this can be added as part of the work for the error messages card: https://trello.com/c/tBLC40PT/1529-error-messages-for-different-field-types
