### ISSUE TITLE
Panels exhibit additional padding from content margin.

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1378]
### Expected behaviour

It should be that equal margins and padding are exhibited on all sides. The final element of content within the panel should remove any bottom margin to make the spacing equal.

### Actual behaviour

The final element within a panel displays `1rem` of bottom margin.

### Technical information

For example to following could resolve this issue:
`.panel.panel--simple *:last-of-type {
    margin-bottom: 0;
}`

#### Browser

All.

#### Operating System
n/a

### Screenshot

**Existing layout:**
![ons-eq-panelcontentmargindefect](https://user-images.githubusercontent.com/22910336/33082166-0060fcfc-ced4-11e7-9e0b-ee0823507887.png)

**Corrected layout:**
![ons-eq-panelcontentmarginnone](https://user-images.githubusercontent.com/22910336/33082174-099c2184-ced4-11e7-9e30-9e69d1d518f2.png)

**Comment by armstrongb** [comment]
This is now raised as an issue in the SDC Pattern Library.

https://github.com/ONSdigital/sdc-global-design-patterns/issues/52

(I don't know if you would like this closed here at this point @ajmaddaford.)

**Comment by bameyrick** [comment]
Resolved in https://github.com/ONSdigital/sdc-global-design-patterns/issues/52
