### ISSUE TITLE
Need test to ensure routing does not skip sections.

### ISSUE THREAD

**Issue by dwyeradam** [ONSdigital/eq-survey-runner#1386]
### Expected behaviour
With navigation added to **test_routing_group.json** you would expect to still be able to route to **Group 2** if that is selected in the Select Group question.

### Actual behaviour
If you add navigation sections to _test_routing_group.json_ then the routing to _Group 2_ from the Select Group question no longer works. It will always go to _Group 1_ regardless.
This works if the groups are within the same sections. It's only when routing is used to skip a section.

### Steps required
We would not actually want to use routing in this manner. To ensure that this does not happen we should add schema validation to ensure that routing is not used to skip sections. Routing should only allow you to route to a group in the same section or the next section.

**Comment by nealedj** [comment]
moved to https://github.com/ONSdigital/eq-schema-validator/issues/25
