### ISSUE TITLE
If 'Label' and 'Value' are not identical Answer is not displayed on Summary

### ISSUE THREAD

**Issue by MIslam92** [ONSdigital/eq-survey-runner#1443]
### Expected behaviour
Should still display and not be affected if they are different

### Actual behaviour
If they are different does not display Answer on the Summary

### Technical information
This should not affect what gets displayed on the Summary page.
Potential fix somewhere in the code we use the label and not the value

#### Browser
All of em

#### Operating System
All of em

**Comment by jonnyshaw89** [comment]
Does this affect all answer types?

**Comment by MIslam92** [comment]
@jonnyshaw89 just checked with different label and value for the Radio answer type and it still got displayed on the Summary page.

**Comment by jonnyshaw89** [comment]
So we think this is specific for Checkbox?

**Comment by MIslam92** [comment]
By the looks of things "Yes"
