### ISSUE TITLE
Some invalid schemas don't fail schema validation on Travis

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#1457]
### Expected behaviour
When a schema is invalid it should fail on Travis

### Actual behaviour
Some invalid schemas don't fail on Travis

### Steps to reproduce the behaviour
See https://github.com/ONSdigital/eq-survey-runner/pull/1434

**Comment by nealedj** [comment]
Also worth noting that #1460 refers to a valid schema that **is** causing Travis to fail.

**Comment by MebinAbraham** [comment]
Fixed in #1465
