### ISSUE TITLE
py-test warning 'TestSessionData' has a __init__ constructor

### ISSUE THREAD

**Issue by shahi645** [ONSdigital/eq-survey-runner#1470]
### Expected behaviour
No pytest warnings

### Actual behaviour
1 pytest warning 

### Steps to reproduce the behaviour
run unit tests with `-rw` to print py.test warning output 

### Technical information
WC1 eq-survey-runner/tests/app/data_model/test_session_store.py cannot collect test class 'TestSessionData' because it has a __init__ constructor

### Screenshot
<img width="1286" alt="screen shot 2018-02-21 at 08 29 35" src="https://user-images.githubusercontent.com/22025926/36470118-b1d97108-16e1-11e8-80a5-ec2fb18bc9cb.png">

**Comment by jonnyshaw89** [comment]
@shahi645 can you be more specific about the command to reproduce?
