### ISSUE TITLE
Border on Currency unit cut off

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1489]
### Expected behaviour
The border should not be cut off

### Actual behaviour
The border is cut off

Issue raised https://github.com/ONSdigital/sdc-global-design-patterns/issues/77

### Screenshot
![img_1800](https://user-images.githubusercontent.com/7594012/37346195-9a5f33ec-26c6-11e8-8d7f-23ca7648d985.PNG)

**Comment by armstrongb** [comment]
Got a browser/OS version for this @jonnyshaw89 ?

**Comment by jonnyshaw89** [comment]
I tested on iPhone X
Both Safari and Chrome
