### ISSUE TITLE
Footer exhibits margin bottom

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1490]
### Expected behaviour

Footer is flush with bottom edge of browser window

### Actual behaviour

It is currently 18px / 1rem above the browser edge

Caused by `.print__hidden` on `.footer2`

_print.scss 
`.print__hidden {
    margin-bottom: 18px;
    margin-bottom: 1rem;
}`

### Steps to reproduce the behaviour

View footer in pre-prod

#### Browser
Found on: Chrome 64 

#### Operating System
Apple - High Sierra

### Screenshot
![ons-eq-footer-margin-issue](https://user-images.githubusercontent.com/22910336/37350524-e64dbe7c-26d0-11e8-856c-f2a9e5d1d81f.png)

**Comment by benhowes** [comment]
Footer2 has been removed in #1710
