### ISSUE TITLE
Edit links misaligned on summary for IE7

### ISSUE THREAD

**Issue by nealedj** [ONSdigital/eq-survey-runner#1496]
#### Browser
IE7

#### Operating System
Windows 7

### Screenshot
<img width="523" alt="screen shot 2018-03-13 at 17 43 50" src="https://user-images.githubusercontent.com/356075/37359701-35987e58-26e6-11e8-973d-a4830a5ea137.png">

**Comment by hamishtaplin** [comment]
Not sure this is worth fixing. Our policy for IE7 is that it should be "functional" rather than pretty.
