### ISSUE TITLE
Currency field misaligned and input indented on IE7

### ISSUE THREAD

**Issue by nealedj** [ONSdigital/eq-survey-runner#1497]
#### Browser
IE7

#### Operating System
Windows 7

### Screenshot
<img width="508" alt="screen shot 2018-03-13 at 17 38 15" src="https://user-images.githubusercontent.com/356075/37359850-8f3ed6d2-26e6-11e8-9c79-b462905a1368.png">

**Comment by hamishtaplin** [comment]
Our browser support for IE7 is "functional", I wouldn't fix this.

**Comment by nealedj** [comment]
CC @armstrongb I'm closing this but it might be something you still want to track for the pattern library.
