### ISSUE TITLE
Footer text weight in Firefox

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1501]
### Expected behaviour
Font weight matches that in other browsers
### Actual behaviour
Font weight is visually heavier
### Steps to reproduce the behaviour
View footer in Firefox
### Technical information
Requires the application of a browser specific fix:
`-webkit-font-smoothing: antialiased;
 -moz-osx-font-smoothing: grayscale;`
when a light colour is used on a dark background (e.g. the footer and buttons)

#### Browser
Firefox 59.0
#### Operating System
High Sierra
#### Existing
![ons-eq-footer-text-ffox59](https://user-images.githubusercontent.com/22910336/37362607-98429154-26ed-11e8-8940-a0e796395bac.png)
#### Fixed (via inspector)
![ons-eq-footer-text-ffox59-inspector-fix](https://user-images.githubusercontent.com/22910336/37362869-5b12e620-26ee-11e8-8644-a27b4ef92273.png)

**Comment by armstrongb** [comment]
(In the example above only the headings have had the fix applied)

**Comment by benhowes** [comment]
@boxadesign this also seems to be still present, might be worth considering as part of #1710

**Comment by boxadesign** [comment]
@benhowes This was an issue with light text on dark background. We've reversed this for the latest footer component and I've checked in FireFox and there isn't the same problem so I think this can be closed.
