### ISSUE TITLE
Inline styles from CDN scripts refusing to apply on Edge 14

### ISSUE THREAD

**Issue by nealedj** [ONSdigital/eq-survey-runner#1502]
### Expected behaviour
Scripts loaded externally from our CDN should be able to apply inline styles.

Manifestation - the show/hide buttons on the introduction page should show/hide the content below them.

### Actual behaviour
When an external script attempts to apply an inline style Edge 14 blocks it.

Manifestation - the show/hide buttons on the introduction page have no effect. The guidance is always shown.

### Steps to reproduce the behaviour
Run the app using Edge 14, check the console for errors and test the show/hide buttons on a questionnaire with an introduction page.

### Technical information
I think this became an issue when the scripts were externalised to the CDN.

#### Browser
Edge 14

#### Operating System
Windows 10

### Screenshot
<img width="1427" alt="screen shot 2018-03-14 at 09 36 32" src="https://user-images.githubusercontent.com/356075/37394675-3a99a2c0-276c-11e8-9045-232c4349c500.png">
<img width="655" alt="screen shot 2018-03-14 at 09 36 15" src="https://user-images.githubusercontent.com/356075/37394677-3ab10578-276c-11e8-9e6c-0c00d34b7cf9.png">

**Comment by nealedj** [comment]
This may not be worth fixing.

The experience will be similar to the non-JS experience for users so it doesn't prevent them using it.
 
The issue is fixed in Edge 15 and 16.

**Comment by hamishtaplin** [comment]
@nealedj What exactly does it block? I think this uses the Accordion component which applies classes/attributes rather than inlining styles onto elements. I don't think we apply inline styles anywhere and we definitely shouldn't be.

**Comment by nealedj** [comment]
It's not clear from the log exactly what is getting blocked. Just says that CSP has blocked an inline style from being applied but IE doesn't seem to provide enough context to work out where.
