### ISSUE TITLE
OGL logo in footer displays incorrectly

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/eq-survey-runner#1505]
### Expected behaviour
OGL svg logo displays as light grey
### Actual behaviour
OGL svg displays as 'off black'
### Steps to reproduce the behaviour
View footer on pre-prod in Browserstack
#### Browser
Safari 10.1.2
Safari 10
Safari 10.3 
#### Operating System
Sierra
iOS on iPhone 7 (Browserstack Safari 10)
iOS on iPad Pro (Browserstack Safari 10.3)
### Screenshot
![bs_macsie_safari_10 1](https://user-images.githubusercontent.com/22910336/37411074-d7c5321c-2799-11e8-9556-e35e1c30b72c.jpg)
#### iPhone 7 (Safari 10)
![bs_realios_mobile_iphone 7-10 0](https://user-images.githubusercontent.com/22910336/37416790-a527df5a-27a6-11e8-8cae-8e6363b82e19.jpg)
![bs_ios_tablet_ipad pro 9 7 inch -10 3](https://user-images.githubusercontent.com/22910336/37418436-1bd32184-27aa-11e8-98b1-cfb69d0989c7.jpg)

**Comment by boxadesign** [comment]
This is no longer an issue @benhowes

**Comment by benhowes** [comment]
👍
