### ISSUE TITLE
environment URL exists and is broken

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#157]
### Expected behaviour
- /environment URL is disabled in production
- /environment URL works or is removed 
### Actual behaviour
- /environment URL is enabled in production
- /environment URL causes an internal server error
### Steps to reproduce the behaviour
- Go here: https://preprod-surveys.eq.ons.digital/environment
#### Browser
- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] MS Edge
- [x] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [x] Windows
- [x] OS X
- [x] iOS
- [ ] Android
#### Screenshot

![internal_server_error](https://cloud.githubusercontent.com/assets/14041600/14428200/00c4e712-fff0-11e5-991d-df76e253ba19.PNG)

**Comment by warrenbailey** [comment]
Fixed" https://github.com/ONSdigital/eq-survey-runner/pull/158
