### ISSUE TITLE
Answered questions getting repeated , ignoring routing ?

### ISSUE THREAD

**Issue by AndrewTorrance** [ONSdigital/eq-survey-runner#1724]
Expected behaviour
When routing between questions , the position of the question should not matter if the routing is set correctly in the questions

### Actual behaviour
See .Example schemas below. Run lms_3_bad.json  when you get to had a paid job answer no , then answer no to all questions . After completing you will get routed back to 'ever-had-a-paid-job-red-1' and enter a repeating loop.

Now run lms_3.json and answer the same way. You will find that you can submit ok. The only difference in these I think is the positioning of the questions .They should route exactly the same 

[Archive.zip](https://github.com/ONSdigital/eq-survey-runner/files/2267191/Archive.zip)

**Comment by jonnyshaw89** [comment]
if you put these schemas in a gist then we can launch them via `quick-launch` with the URL?

**Comment by AndrewTorrance** [comment]
Closing issue . Found the cause . It was routing back to an element with a lower index and then getting removed from completed blocks . Now I need to work out if LMS can route forward only.
