### ISSUE TITLE
started_at wiped from metadata when a questionnaire is re-launched

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1731]
### Expected behaviour
When a questionnaire is re-launched the `started_at` date should remain

The `started_at` value should be set when the 1st page is posted (generally introduction)

### Actual behaviour
When a questionnaire is re-launched the metadata is overwritten which wipes the `started_at` date.
Question:  Should our metadata be immutable?

The `started_at` value is set when the 1st answer is sent, rather than when the "Start survey" button is pressed

### Steps to reproduce the behaviour
Launch from launcher and name a note of `RU Ref` and `Collection Exercise SID`
Answers some questions
Launch again from launcher using the same `RU Ref` and `Collection Exercise SID`

**Comment by bitdivision** [comment]
Can we rely on the start survey button always being present?

**Comment by jonnyshaw89** [comment]
@bitdivision no, so the 1st form submit
