### ISSUE TITLE
Error pages expose survey name

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#176]
### Expected behaviour
- The name of the survey is not shown on error pages when the user is not authenticated.
### Actual behaviour
- Anyone visiting https://eq.ons.gov.uk is shown the name of the MCI survey.
### Steps to reproduce the behaviour
- Go to https://eq.ons.gov.uk without logging in
- See the error page contains "Monthly Business Survey - Retail Sales Index" in the header.
#### Browser
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] MS Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [] Windows
- [x] OS X
- [ ] iOS
- [ ] Android
### Screenshot

<img width="935" alt="screen shot 2016-04-14 at 10 58 11" src="https://cloud.githubusercontent.com/assets/14041600/14524560/e313d9ec-0230-11e6-9eb0-c1abdf6cf7d4.png">

**Comment by weapdiv-david** [comment]
Before we can _properly_ do this, we need to update _all_ the views to provide more information to the template layer...

The information we would need to provide would be the survey title, and whether or not we are actually in a "questionniare session".  This raises larger, as-yet-unresolved issues around the user journey through eQ.

The simplest approach at this stage would be to remove the beta-banner from the error page, while we consider the journey through eQ.

**Comment by hamishtaplin** [comment]
Happy to just remove banner, @alexmorris?

**Comment by alexmorris** [comment]
@hamishtaplin sure, pull it out or better still redirect to the error page outside of the runner template?

**Comment by hamishtaplin** [comment]
@alexmorris we don't have that additional error template at the moment.

**Comment by weapdiv-david** [comment]
I can override the beta banner block in the error template with an empty block, easily enough.  If @hamishtaplin and @alexmorris are happy for me to do that, I'll put up a pull request shortly

**Comment by weapdiv-david** [comment]
pushed the change, updated and re-opened the original pull request

**Comment by collisdigital** [comment]
Confirmed fixed by #181
