### ISSUE TITLE
Focus from error navigation

### ISSUE THREAD

**Issue by stevevic** [ONSdigital/eq-survey-runner#178]
### What should happen

When an eror is identified and the error message box appears at the top of the page, if the user selects 'Go to this error' the screen and cursor should navigate to the error
### Actual behaviour

the screen view navigates to the field in error, but cursor does not - need to either tab down or click in required field
### Steps to reproduce the behaviour

fill out RSI form with error e.g. no entry for total retail sales, press return, get error message and then select Go to error
#### Browser:
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] MS Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [x] Windows
- [ ] OS X
- [ ] iOS
- [ ] Android
### Screenshot

[Error navigation.docx](https://github.com/ONSdigital/eq-survey-runner/files/218950/Error.navigation.docx)

**Comment by hamishtaplin** [comment]
Having spoken to @alexmorris, decided to leave this for now as the current UX is better for the majority of users.
