### ISSUE TITLE
Summary display

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#182]
### Expected behaviour

The summary page should be in tabular format
For test survey 1_888.json, integer fields are appearing below the question rather then next to it
### Steps to reproduce the behaviour

Fill in survey id 1_888.json and go to the summary page
#### Browser
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] MS Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [x] Windows
- [ ] OS X
- [ ] iOS
- [ ] Android

**Comment by collisdigital** [comment]
Screenshot?

**Comment by hamishtaplin** [comment]
Does this have an associated branch?

**Comment by collisdigital** [comment]
Fix reverted on master, needs new PR to resolve
