### ISSUE TITLE
eQ not failing gracefully upon naughty string entry into a text field

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1824]
### Expected behaviour
Must have a better error message with eQ look and feel

### Actual behaviour
Simply displays a broken screen (without eQ style look and feel) with  Error (Gateway) (possibly a WAF block) PFA

### Steps to reproduce the behaviour
Launch test_textfield schema
Enter a naughty string. example: <script>alert(123)</script>
and click save and continue

#### Browser
Chrome

### Screenshot
![waf_error](https://user-images.githubusercontent.com/21335236/46865444-8113e580-ce15-11e8-8190-4c9a830f6819.png)

**Comment by dcdarrell9** [comment]
@yoganandkunche I can't replicate this locally or on staging/preprod, any guidance?
