### ISSUE TITLE
Error 500 for LMS upon [save and submit later] on final submission screen

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#1869]
### Expected behaviour
Must return to account or RH page

### Actual behaviour
Giving error 500

### Steps to reproduce the behaviour
Launch LMS_2
Navigate to the final submission screen and click [save and complete later]

#### Browser
Chrome

**Comment by MebinAbraham** [comment]
Issue when `Confirmation` type has questions but not answers. Affects other live surveys such as `e_commerce`.
```
  File "/Users/abrahm/Documents/projects/eq-survey-runner/app/helpers/form_helper.py", line 121, in disable_mandatory_answers
    for answer_json in question_json['answers']:
KeyError: 'answers'
```
