### ISSUE TITLE
Remove base64 decoding of submitted answers and session

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#1898]
In order for the app to continue working as expected during deployment of https://github.com/ONSdigital/eq-survey-runner/pull/1887:
- Session data written by an old instance of the app (base 64 encoded) needs to be readable by the new version 
- Submitted data saved by an old instance of the app (base64 encoded) needs to be readable by the new version. 

Once the new app is deployed and all old sessions have expired, we should remove this code as all session data and submitted answers will no longer be base64 encoded.

**Comment by bitdivision** [comment]
Including tests
