### ISSUE TITLE
Totaliser uses whole numbers to add up.

### ISSUE THREAD

**Issue by MebinAbraham** [ONSdigital/eq-survey-runner#1902]
### Expected behaviour
Should use decimals if specified.
### Actual behaviour
https://github.com/ONSdigital/eq-survey-runner/blob/master/app/assets/js/app/modules/totaliser.js#L21
Since `parseInt` is used, decimals are ignored. 
So if the condition is the total must be 100. You can do 10.99 + 90.99 and it would still be valid, but it shouldn't be.
### Steps to reproduce the behaviour
Use `test_total_breakdown.json` to test.

**Comment by dwyeradam** [comment]
Since this is an old feature I don't feel we should be using the totaliser in runner. To fix this I would recommend deleting the code around this pattern altogether.
