### ISSUE TITLE
405 Method Not Allowed returns a 500 error

### ISSUE THREAD

**Issue by MebinAbraham** [ONSdigital/eq-survey-runner#1939]
### Expected behaviour
Return a 404?
### Actual behaviour
Returns a 500
### Steps to reproduce the behaviour
If you do `/flush` on runners base URL, you will get:
https://github.com/ONSdigital/eq-survey-runner/blob/master/app/views/flush.py#L18
```
  File "/Users/abrahm/.virtualenvs/eq-survey-runner-TQNVnq61/lib/python3.6/site-packages/werkzeug/routing.py", line 1580, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
127.0.0.1 - - [11/Dec/2018 16:15:34] "GET /flush HTTP/1.1" 500 -
```
This is the current behaviour in all environments.

If it is not a valid request, we should probably return a 404?.

**Comment by jonnyshaw89** [comment]
Why would we return a 404? we just want to handle and throw it as a 405?
It 500s because we don't handle it in https://github.com/ONSdigital/eq-survey-runner/blob/master/app/views/errors.py

**Comment by MebinAbraham** [comment]
Wasn't sure if exposing it as a 405 would be the best since its specially for upstream use. But yea whatever is best.

**Comment by jonnyshaw89** [comment]
Seems sensible to return the actual code rather then mask it with something else
