### ISSUE TITLE
Maximum Character Limit not Enforced on Comments

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#197]
### Expected behaviour

Unable to enter additional characters into the comments box after the limit has been hit (2000 characters).
### Actual behaviour

It is not possible to enter more than the maximum character count.
### Steps to reproduce the behaviour
- Start the MCI survey
- Go to the comments box
- Fill it with the maximum number of characters (2000)
- Move the cursor to the middle of the comments text
- Press a letter on the keyboard
- Observe that the additional character is permitted.
#### Browser
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] MS Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [x] Windows
- [ ] OS X
- [ ] iOS
- [ ] Android

**Comment by hamishtaplin** [comment]
Marking this as "wontfix" as it's an edge case and this feature will be re-written at some point.
