### ISSUE TITLE
HTTP 500 error on Save and sign out when validation fails

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#2051]
### Expected behaviour

When I click save and sign out and the page fails validation, the page should be redisplayed with the validation error.

### Actual behaviour
HTTP 500 error is displayed.

### Steps to reproduce the behaviour
- Open the test_variants_question schema
- Navigate to the age question
- Enter something invalid e.g. letters
- Click 'Save and sign out'

**Comment by MebinAbraham** [comment]
Fixed by ☝️
