### ISSUE TITLE
Unit tests fail between 12am and 1am during BST

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/eq-survey-runner#2101]
### Expected behaviour
Unit tests should pass at any time/date

### Actual behaviour
Certain unit tests fail between the hours of 0000 and 0100 when the locale TZ is BST.

### Steps to reproduce the behaviour
Run the unit tests in the summer after 12am and before 1am. Or maybe mock the time out!

### Technical information
The test that fails compares two date objects for equality, which fails. This is likely related to one date object being created using UTC as the TZ and the other being created using BST as the TZ.

**Comment by bitdivision** [comment]
I think this has been resolved by @ajmaddaford ?
