### ISSUE TITLE
Invalid Dates from RRM Cause Internal Server Error

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#236]
### Expected behaviour
- Default error page is shown when invalid dates are supplied from RRM
### Actual behaviour
- Internal server error is shown.
### Steps to reproduce the behaviour
- Go to /dev page
- Enter 2016-13-30 for "REF P End Date"
- Hit submit
- See "Internal Server Error" message
#### Browser
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] MS Edge
- [ ] Internet Explorer 11
- [ ] Internet Explorer 10
- [ ] Internet Explorer 9
- [ ] Internet Explorer 8
- [ ] Internet Explorer 7
- [ ] Internet Explorer 6
- [ ] Other (please state below)
#### Operating System
- [x] Windows
- [ ] OS X
- [ ] iOS
- [ ] Android
### Screenshot

![image](https://cloud.githubusercontent.com/assets/14041600/15431595/84509a10-1ea2-11e6-94a2-0dfd52f24269.png)

**Comment by weapdiv-david** [comment]
This is due to the date not being parsed before piping...  The renderer receives a None object.
I can catch (and ignore) the exception in the piping forcing the template text to be displayed on the screen, but I'm wondering if this is really the best way to handle it.

If RRM send us an invalid date, where should we catch it?

**Comment by collisdigital** [comment]
The dates are in a defined format we have agreed, so if they are invalid when received it implies the data is corrupted and a possible security problem, I suggest upon reception of the JWT we parse the dates and fail authentication if they are invalid...

**Comment by weapdiv-david** [comment]
I had a brief conversation with @warrenbailey about this before I left and we arrived at a similar conclusion. We are going to redactor the way the data is received from RRM so we can handle this properly

**Comment by collisdigital** [comment]
:+1:

**Comment by warrenbailey** [comment]
I'll look at refactoring this now
