### ISSUE TITLE
Mandatory Checkboxes and radio boxes are no longer mandatory

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#248]
### Expected behaviour

Mandatory checkboxes and radio boxes don't block submission
### Actual behaviour

The form allows submission without them being completed. The response object is no longer including them, so they get skipped
### Steps to reproduce the behaviour

Use star wars in dev and submit an empty form
#### Browser

Chrome
#### Operating System

Windows

**Comment by dhilton** [comment]
This has been closed through #264
