### ISSUE TITLE
Preceeding zeros are not handled properly

### ISSUE THREAD

**Issue by shilpabasu** [ONSdigital/eq-survey-runner#263]
### Expected behaviour

When a user enters preceding zeros, they should be removed
### Actual behaviour

Preceding zeros are not removed and passed on to the downstream system
### Steps to reproduce the behaviour -
1. Open an eQ survey
2. Enter preeceding zeros (0000000000000000000000001) as test data in various fields.
3. Submit Survey
4. Verify the image file and other files generated for down stream system.
#### Browser

IE11
#### Operating System

Windows 7
### Screenshot

![form_page1](https://cloud.githubusercontent.com/assets/17923832/16190505/7c063d68-36d7-11e6-80d3-6ab5ff26d810.PNG)
![form_page2](https://cloud.githubusercontent.com/assets/17923832/16190689/73be0f40-36d8-11e6-9228-5698511b4526.PNG)
[Output_DataFile.txt](https://github.com/ONSdigital/eq-survey-runner/files/323163/Output_DataFile.txt)
![output_imagefile](https://cloud.githubusercontent.com/assets/17923832/16190690/73c2a2ee-36d8-11e6-87c5-8ef55a37fdc5.jpg)
![summary1](https://cloud.githubusercontent.com/assets/17923832/16190688/73bbecd8-36d8-11e6-90b3-cfd08cbfdcc8.PNG)
![summary2](https://cloud.githubusercontent.com/assets/17923832/16190691/73c70e42-36d8-11e6-97e4-1ddb8daf8ad5.PNG)

**Comment by dhilton** [comment]
Has this been verified to be fixed by #341 ? @weapdiv-david

**Comment by weapdiv-david** [comment]
No, we're still sending strings downstream at present.  Will need to verify with the SDX team that we can change the format to send integers, then update our downstream tests accordingly

**Comment by collisdigital** [comment]
Confirmed this is fixed by #368 on pre-prod. Closing.
