### ISSUE TITLE
When generating json schemas from code, data directory needs to be present or dev page fails.

### ISSUE THREAD

**Issue by dhilton** [ONSdigital/eq-survey-runner#280]
### Expected behaviour

When you hit `/dev` you're presented with a development page in development environments and preprod.
### Actual behaviour

That page error's 500.
### Steps to reproduce the behaviour

Visit preprod url `/dev`
### Technical information

Logs report an error due to lack of `data` directory.
#### Browser

ALL
#### Operating System

ALL

**Comment by warrenbailey** [comment]
It's broken again, elastic beanstalk ignores the .gitignore file

**Comment by dhilton** [comment]
OK - revert the .gitignore change to the README change but keep the filename filter aspect. Bother.

**Comment by dhilton** [comment]
This has been fixed. Closin'
