### ISSUE TITLE
Possible to Submit with Errors

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#328]
### Expected behaviour

Final submission is always prevented if the questionnaire has any responses that result in an error.
### Actual behaviour

It is possible to submit the questionnaire with responses that cause errors
### Steps to reproduce the behaviour
- Launch the same questionnaire (identifiers etc.) with two different browsers
- Complete questionnaire without errors up to summary page
- On other browser edit a question response to cause an error
- On the original browser hit submit
- Observe that submission is successful despite erroneous responses.
#### Browser

Any (tested with Chrome and Safari as secondary browser)
#### Operating System

Any
### Screenshot

N/A

**Comment by collisdigital** [comment]
To avoid a race condition here we probably need to validate the exact data that is submitted (i.e. retrieve data, validate it, then submit it) without going back to the database (otherwise between the validate and submit step the data could have changed).

**Comment by collisdigital** [comment]
Following on from this, whilst developing https://github.com/ONSdigital/eq-performance-test/pull/4/ it became clear that we only validate the block/page responses if the fields are included in the POST parameters by the browser, so for example, if you just send the save and continue button/value and none of the fields on the page then all validation is skipped for those fields that are missing. Talking with @dhilton this isn't desirable behaviour and we should validate all values on the page even if the respondent doesn't submit them...

**Comment by weapdiv-david** [comment]
Is this still the case as the validation refactor was supposed to fix this along with many other issues?

**Comment by warrenbailey** [comment]
Just confirmed that the validator refactor has fixed the second problem.

**Comment by collisdigital** [comment]
👍
