### ISSUE TITLE
Date Error message incomplete

### ISSUE THREAD

**Issue by stevevic** [ONSdigital/eq-survey-runner#346]
### Expected behaviour

Full Date error message displayed to respondent
### Actual behaviour

Partial error message displayed to respondent
### Steps to reproduce the behaviour

Start business survey 0205 (or any other RSI related survey)
Provide 2 dates that generate an error message (e.g. dates the same, From is after To date)
Submit form - note error message
#### Browser

Chrome
#### Operating System

Windows 7
### Screenshot

![image](https://cloud.githubusercontent.com/assets/17979130/17327898/81c8d128-58b2-11e6-958d-21fb77c163a0.png)

**Comment by weapdiv-david** [comment]
Fix for this is currently in master. @stevevic can you close it?

**Comment by collisdigital** [comment]
Confirmed fixed on master
