### ISSUE TITLE
Date range widget has 'from' as both legends

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#360]
### Expected behaviour

A date range should use the legends 'from' and 'to'.
### Actual behaviour

Both legends use 'from' as a legend.
### Steps to reproduce the behaviour
- Start a questionnaire (eg. `10215.json`)
- Witness the erroneous legends
### Screenshot

<img width="905" alt="screenshot 2016-08-09 08 47 38" src="https://cloud.githubusercontent.com/assets/930398/17508984/91e81b10-5e0f-11e6-8161-067fc8f7768a.png">

**Comment by dhilton** [comment]
Fixed.
