### ISSUE TITLE
When editing comments, cursor moves back to end of line

### ISSUE THREAD

**Issue by shilpabasu** [ONSdigital/eq-survey-runner#363]
### Expected behaviour

Cursor should remain before "e"
### Actual behaviour

But cursor moves to end of line
### Steps to reproduce the behaviour
1. Go to any eQ survey on IE11
2. Enter a string in comments box "This is a test surey"
   3 .Now, go and edit the string by adding "v" in "surey"

RTC Defect Number 93562
#### Browser

Internet Explorer 11
#### Operating System

Windows 7

**Comment by dhilton** [comment]
This maybe related: http://stackoverflow.com/questions/8219639/stop-cursor-from-jumping-to-end-of-input-field-in-javascript-replace

**Comment by collisdigital** [comment]
Agreed to solve this by changing the frontend to allow overflow of character limit (like Twitter).
