### ISSUE TITLE
Saved data not retrieved after new Deployment

### ISSUE THREAD

**Issue by shilpabasu** [ONSdigital/eq-survey-runner#364]
### Expected behaviour

EQ window should launch with the saved information where we closed the EQ window in point 9
### Actual behaviour
1. EQ launched from Starting without the saved information
2. Filled all the data and clicked on Save & Continue button
3. Error 500 displayed
### Steps to reproduce the behaviour
1. Register a user for MCI survey with instrument file( MCI)
2. Launch and login to the external
3. Verify the status as 'NOT STARTED'
4. Click on 'START' button
5. EQ window is launched
6. Start the survey and complete some fields with data
7. Click on 'Save and Continue' button
8. Close the window
9. Logout from the application
10. Mean while EQ deployment is done for the new release
11. Login into External
    13 Click on 'START' button on portfolio page
#### Browser

IE 11,  Pre-prod
#### Operating System

Windows 7
### Screenshot

![c--users-raom-downloads-error500](https://cloud.githubusercontent.com/assets/17923832/17517127/cf5fa04c-5e39-11e6-823d-2ef06904252c.PNG)

**Comment by collisdigital** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CAQgrouT&#x2F;503-eq-survey-runner-364-saved-data-not-retrieved-after-new-deployment-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> eq-survey-runner: #364 - Saved data not retrieved after new Deployment (Issue)</a>

**Comment by collisdigital** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CAQgrouT&#x2F;503-eq-survey-runner-364-saved-data-not-retrieved-after-new-deployment-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> eq-survey-runner: #364 - Saved data not retrieved after new Deployment (Issue)</a>
