### ISSUE TITLE
POST data field length not validated in backend

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#366]
### Expected behaviour

All fields submitted in a POST request are length limited by the backend
### Actual behaviour

Some fields (e.g. comments) aren't length limited in the backend.
### Steps to reproduce the behaviour

Send POST data for a comment field that exceed 2000 characters
#### Browser

All
#### Operating System

All
### Screenshot

N/A

**Comment by collisdigital** [comment]
It seems the frontend limit has vanished as well on master:
![image](https://cloud.githubusercontent.com/assets/14041600/17603294/4eafee72-6008-11e6-884e-fbd9016f9dc0.png)

@hamishtaplin  ?

**Comment by warrenbailey** [comment]
I suggest we check the comments size backend in the type validation, but we also set a MAX_CONTENT_LENGTH

**Comment by warrenbailey** [comment]
The second issue is raised here #370

**Comment by dhilton** [comment]
I think that both this issue and #370 have been merged and fixed. Can you confirm @collisdigital ?

**Comment by collisdigital** [comment]
Confirmed this is fixed by #366 on pre-prod. Closing.
