### ISSUE TITLE
Guidance not Being Displayed

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#367]
### Expected behaviour

Guidance hint and text is shown to respondent
### Actual behaviour

Guidance hint/text is not visible
### Steps to reproduce the behaviour
- Start a survey with guidance against a question
- Observe that no guidance is visible
#### Browser

All
#### Operating System

All
### Screenshot

<img width="788" alt="screen shot 2016-08-11 at 15 28 20" src="https://cloud.githubusercontent.com/assets/14041600/17591985/669e8ffa-5fd8-11e6-8dbc-d7e29dae660b.png">

**Comment by dhilton** [comment]
Fixed and deployed to preprod.
