### ISSUE TITLE
Error status is not updated

### ISSUE THREAD

**Issue by shilpabasu** [ONSdigital/eq-survey-runner#374]
### Expected behaviour

Error for incorrect dates shouldn't be displayed (step 6)
Value for Retail Turnover shouldn't be retained (Step 9)
### Actual behaviour

Error for incorrect dates is displayed (step 6)
Value for Retail Turnover is retained (Step 9)
### Steps to reproduce the behaviour
1. Go to questionnaire page (MCI)
2. Enter incorrect dates (From Date> To Date)
3. Enter Retail Turnover
4. Click on Save & Continue
5. Error message is displayed for Dates (as Expected)
6. Now correct the dates and remove the value for Retail Turnover (mandatory field)
7. Click on Save & Continue
8. Error message for both dates and retail value is displayed.
9. Value of retail turnover (from step 3) is retained.
### Technical information

IE11
#### Browser

IE11
#### Operating System

windows 7
### Screenshot

![datevalidation1](https://cloud.githubusercontent.com/assets/17923832/17621150/5f3ff332-6089-11e6-91a3-6ccd82fe757b.PNG)
![validation2](https://cloud.githubusercontent.com/assets/17923832/17621149/5f3cc018-6089-11e6-8e35-0231cc74d01f.PNG)

**Comment by collisdigital** [comment]
Confirmed, entering a value, then later removing it causes the previous value to be displayed in the input box but with an error that the value is missing.

**Comment by collisdigital** [comment]
Confirmed this is fixed by #385 on pre-prod. Closing.
