### ISSUE TITLE
Checkbox and Radio values not Whitelisted on POST

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#380]
### Expected behaviour
- It is only possible to submit a valid/expected value for a radio/checkbox.
### Actual behaviour
- Any value is accepted for a radio/checkbox on POST and stored/submitted.
### Steps to reproduce the behaviour
- Launch Star Wars questionnaire
- Choose dark side
- When presented with how many ships radio option 1 or 2 edit the form (browser inspect) and change the value to '3' for the '2' radio option.
- Submit and continue
- You are now allowed to choose 3 ships and 3 is the submitted/stored value.
- The same can be done for changing checkbox values, whatever is POSTed is stored and submitted, checking the summary screen shows this.
#### Browser

All
#### Operating System

All
### Screenshot

N/A

**Comment by jonnyshaw89** [comment]
This issue has been complicated by how the text entry values for 'other' are stored.
This essentially allows for a value that isn't an expected value to be allowed through.

**Comment by collisdigital** [comment]
I think this should possibly wait for after the WTForms work.

**Comment by collisdigital** [comment]
Appears to be related to #565

**Comment by collisdigital** [comment]
@LJBabbage is this resolved after the 'Other' checkbox/radio changes?

**Comment by collisdigital** [comment]
This is now resolved by the use of WTForms: 

![image](https://cloud.githubusercontent.com/assets/14041600/23404760/85fe9b00-fdae-11e6-9149-55f043442195.png)
