### ISSUE TITLE
submitted_at timestamp in SDX JSON payload is not UTC

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#382]
### Expected behaviour

The submitted_at property of the SDX JSON payload should be in UTC
### Actual behaviour

The submitted_at property of the SDX JSON payload is in GMT. This results in the images generated by SDX for Common Software having a time one hour in the future.
### Steps to reproduce the behaviour

Submit a survey through the survey runner and check that the image generated by SDX has the right date and time.
### Technical information

The documentation at https://github.com/ONSdigital/ons-schema-definitions/blob/master/docs/dx-eq.rst says that datetimes are UTC unless a timezone identifier is given.
#### Browser

N/A
#### Operating System

N/A
### Screenshot

N/A

**Comment by warrenbailey** [comment]
Fixed by https://github.com/ONSdigital/eq-survey-runner/pull/386
