### ISSUE TITLE
Possible to submit with incomplete survey data

### ISSUE THREAD

**Issue by dhilton** [ONSdigital/eq-survey-runner#384]
### Expected behaviour

You can get to the summary page click edit answers, then click back in the browser and then be represented with your answers.
### Actual behaviour

When you click edit your answers from the summary and then click the browser back button returning you to the summary, you loose your responses.
#### Browser

All
#### Operating System

All

**Comment by warrenbailey** [comment]
As a quick fix, we're going to block access to the summary page unless the questionnaire manager believes thats where you should go next. This means that the back button request will end up redirecting back to your last location.

As a longer term fix we're adjusting how the linked list works, so state is not archived (and hence lost) on get requests.
