### ISSUE TITLE
After starting the survey when [previous] is clicked user can no longer start the survey

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#402]
### Expected behaviour

User must be able to click on [Get Started] and start answering the questions
### Actual behaviour

Clicking [Get Started] does not seem to do anything
### Steps to reproduce the behaviour

1) Launch and 0102/0203 survey click on [Get Started]
2) Click on [Previous]
3) Click on get Started again
#### Browser

Google Chrome

**Comment by collisdigital** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yupD0kh7&#x2F;564-eq-survey-runner-402-after-starting-the-survey-when-previous-is-clicked-user-can-no-longer-start-the-survey"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> eq-survey-runner: #402 - After starting the survey when [previous] is clicked user can no longer start the survey</a>
