### ISSUE TITLE
Display issues on IE 6/7/8/9 in Win 7 & XP and Galaxy Tab

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#412]
### Expected behaviour

  New base theme must fit in as expected on all browsers across different operating systems
### Actual behaviour

Issue 1) Display issues while restoring IE 6/7/8/9 browsers (Please find attached screenshot)
issue 2) Display of header on Samsung galaxy tab is not as expected
### Steps to reproduce the behaviour

Launch RSI/MCI survey on IE 6/7/8/9 in Win XP/7 using browsers stack
Restore the browser and shrink the browser
#### Browser

1) IE 6/7/8/9
2) Google chrome
#### Operating System

1) Win XP/7
2) Galaxy Tab (Android)
### Screenshot

<img width="1280" alt="screen shot 2016-09-06 at 16 52 39" src="https://cloud.githubusercontent.com/assets/21335236/18281086/6a79c4c0-7453-11e6-818b-57b4136a9dee.png">
<img width="465" alt="screen shot 2016-09-06 at 16 57 12" src="https://cloud.githubusercontent.com/assets/21335236/18281087/6a7b5ae2-7453-11e6-82aa-1b75b6250045.png">

**Comment by yoganandkunche** [comment]
CrossBrowser testing coverage matrix.

![crossbrowser testing coverage](https://cloud.githubusercontent.com/assets/21335236/18305474/a944dfa0-74df-11e6-81da-2a24b0df341b.png)

**Comment by collisdigital** [comment]
@hamishtaplin @yoganandkunche @bennpearson what's the status of this defect since we moved the default theme to the new one?

**Comment by yoganandkunche** [comment]
Retested the issue and it works fine after we had the new theme
