### ISSUE TITLE
Non mandatory fields fail validation if a previous value is enter then removed

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#417]
### Expected behaviour

If a non mandatory field is populated, which fails validation but then the value is removed, validation should pass
### Actual behaviour

The first validation failure is presented to the user and you can only preceed by refilling the field
### Steps to reproduce the behaviour

Open 1_205.json, fill in the field 'What was the value of the business's total sales of clothing and footwear?' with text. See the error message appear, now empty the question and submit, see the error message still exists even though it is non-mandatory

**Comment by iwootten** [comment]
Works for me!
