### ISSUE TITLE
RSI - '0' values entered for input are not sent to sdx

### ISSUE THREAD

**Issue by iwootten** [ONSdigital/eq-survey-runner#422]
### Expected behaviour

All zero '0' values entered by the the user are passed as part of the payload to sdx.
### Actual behaviour

Zero value fields are not sent in payload.
### Steps to reproduce the behaviour

Launch an RSI 0112 form type enter '0' for Total Retail sales and submit the survey.
### Screenshot

https://cloud.githubusercontent.com/assets/21335236/18432642/00ff3854-78db-11e6-8edb-3d02033cec18.png

On further investigation, it would seem all values entered as '0' are not passed to sdx. The screenshot below show the data sent when entering 0 values for all numeric fields on rsi.

<img width="924" alt="screen shot 2016-09-12 at 12 44 15" src="https://cloud.githubusercontent.com/assets/3598161/18434728/b7d46008-78e6-11e6-917a-08be07a22cf5.png">

**Comment by stevevic** [comment]
SV Update:  some Zero values do appear to be getting through to Common Software (CS), but not to the image.  Total Turnover (question id 20), for example, should be a mandatory field and cases should fail if not included in the CS feed.
Reports from the business team:
MCI companies ref 50000042790. Zero values entered for 3 out of their 6 categories 
RSI Reference 49908945331 returned their RSI eQ with zero Total  T/O - this is what common software displays. The image though does not display a 0  for the total T/O field, instead the field is blank

**Comment by iwootten** [comment]
@stevevic Here's the outputs from sdx given the above input example passed by eq, none of the outputs include data where it hasn't been passed. Would common software display these values as zero if they hadn't received them?

Image
![screen shot 2016-09-13 at 09 38 54](https://cloud.githubusercontent.com/assets/3598161/18467405/b5b98fb2-7997-11e6-8172-39ee399268bf.png)

PCK
![screen shot 2016-09-13 at 09 42 12](https://cloud.githubusercontent.com/assets/3598161/18467406/b5bd2adc-7997-11e6-9c6e-f248dff758a3.png)

Receipt
![screen shot 2016-09-13 at 09 42 24](https://cloud.githubusercontent.com/assets/3598161/18467404/b5b8a700-7997-11e6-9685-1cfb88290979.png)

**Comment by stevevic** [comment]
@iwootten Hi Ian - the PCK file looks decidely dodgy - should have additional values for questions 0020, 0050 and 0146, all of which are mandatory.  For 0020 & 0050 then they should include the user response, even if this is 0 (and entry to the eQ for these fields should be mandatory (we can check against the schema), for 0146 this is a boolean value based on whether or not the respondent has entered any comments.

**Comment by iwootten** [comment]
@stevevic The open pull request in https://github.com/ONSdigital/eq-survey-runner/pull/424 resolves all these. EQ doesn't pass any values, so sdx doesn't enter data for the fields. Here's the same again with the fix in place.

<img width="1024" alt="screen shot 2016-09-13 at 10 44 46" src="https://cloud.githubusercontent.com/assets/3598161/18469288/89c1237c-799f-11e6-8650-ed1ffd132189.png">

![screen shot 2016-09-13 at 10 50 46](https://cloud.githubusercontent.com/assets/3598161/18469400/ff52a4bc-799f-11e6-9ca2-483c7b18fb59.png)
![screen shot 2016-09-13 at 10 50 37](https://cloud.githubusercontent.com/assets/3598161/18469402/ff55a964-799f-11e6-8630-bccff43c5644.png)
![screen shot 2016-09-13 at 10 50 54](https://cloud.githubusercontent.com/assets/3598161/18469401/ff546144-799f-11e6-8db1-788a31c7c0f6.png)
