### ISSUE TITLE
eQ Survey allows user to enter '-0' in numeric only fields

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#429]
### Expected behaviour

Must not allow user to enter '-0' in numeric fields and must throw an error when [save and continue] is clicked
### Actual behaviour

Allows to enter '-0' and is displayed as '-0' on summary screen and Image files
### Steps to reproduce the behaviour

Go to any numeric field on any eQ survey and entry '-0'
Click on [Save and Continue]
#### Browser

Chrome
![minus zero](https://cloud.githubusercontent.com/assets/21335236/18545214/13ba7560-7b30-11e6-9cf7-ce3d8e846edf.png)

**Comment by collisdigital** [comment]
@yoganandkunche can you confirm if this affects downstream systems (other than the image containing it?)

**Comment by yoganandkunche** [comment]
@collisdigital: After the improve summary screen development the summary screen and the image files does not display the -0 zero anymore so I don't see any impact on the business. I think the defect can be closed.
![-0](https://cloud.githubusercontent.com/assets/21335236/18948532/5e9f9b96-862f-11e6-8a63-b102d8c3466b.png)

**Comment by collisdigital** [comment]
Closing as discussed.
