### ISSUE TITLE
Error 401: when user clicks on Submit Answers button twice when network is slow 

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#458]
### Expected behaviour

Must not error when the user clicks on the [submit answer] button multiple times 
### Actual behaviour

error 401 when the user clicks on the [submit answer] button multiple times 
### Steps to reproduce the behaviour

1) Launch any survey 
2) Fill in the mandatory fields
3) Slow down the network  and click on [Submit Answers] more then once
#### Browser

All browsers
### Screenshot

![screen shot 2016-09-23 at 11 39 01](https://cloud.githubusercontent.com/assets/21335236/18783185/61b378fe-8182-11e6-8b28-db30511262c0.png)

**Comment by collisdigital** [comment]
System working as designed. This has been moved into the backlog for 2017 as a feature development, not a defect.
