### ISSUE TITLE
Two same surveys for different months when launched contains 'data' even when Get Started is clicked for the first time.

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#492]
### Expected behaviour

So data/errors exists for these surveys even though they are just started.

**_Note**_ Issue is intermittent.
### Actual behaviour

Both the surveys must not contain any previously saved data.
### Steps to reproduce the behaviour

Launch two surveys of the same type simultaneously (each for different period (month))
Click on [Get Started] for both the survey's

**Comment by collisdigital** [comment]
Has anyone seen this recently? Suggest we close this if no reccurrance in the last month?

**Comment by benjefferies** [comment]
I haven't noticed the test fail

**Comment by jonnyshaw89** [comment]
I see no harm in closing and re-opening if it occurs again

**Comment by collisdigital** [comment]
Closing as not seen recently.
