### ISSUE TITLE
First link not Skip to Content

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#501]
### Expected behaviour

The first link on all screens is "Skip to content"
### Actual behaviour

The support phone number is the first link
### Steps to reproduce the behaviour
- Tab into any screen, observe that the phone number is selected first.
#### Browser
- Chrome (latest)
#### Operating System
- macOS Sierra
### Screenshot

<img width="381" alt="screen shot 2016-10-19 at 09 11 01" src="https://cloud.githubusercontent.com/assets/14041600/19510679/257d34f6-95dc-11e6-8aff-7f054d1fd1ee.png">

**Comment by yoganandkunche** [comment]
Defect passed QA
