### ISSUE TITLE
Footer not sticky (whitespace below)

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#506]
### Expected behaviour

Footer always sticks to the bottom of the screen
### Actual behaviour

On pages without much content the footer floats above the bottom (leaving whitespace below it)
### Steps to reproduce the behaviour

View https://preprod-surveys.eq.ons.digital/information/multiple-surveys as an example, observe whitespace below the footer.
#### Browser

Chrome
#### Operating System

macOS Sierra
### Screenshot

<img width="632" alt="screen shot 2016-10-19 at 12 47 56" src="https://cloud.githubusercontent.com/assets/14041600/19517748/e3ae5810-95fa-11e6-80ab-8e86a3a08064.png">

**Comment by yoganandkunche** [comment]
Defect passed QA
