### ISSUE TITLE
Phone Number Focus not Inverted

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#507]
### Expected behaviour
- When selecting the phone number the focus style inverts the text colour to improve contrast against the background.
### Actual behaviour
- The phone number has a background highlight but the text remains black lacking contrast.
### Steps to reproduce the behaviour
- Tab onto the phone number in the header and observe the text is black with a dark blue background (see screenshot).
#### Browser

Chrome
#### Operating System

macOS Sierra
### Screenshot

<img width="381" alt="screen shot 2016-10-19 at 09 11 01" src="https://cloud.githubusercontent.com/assets/14041600/19517811/57e472dc-95fb-11e6-8381-10cae9388398.png">

**Comment by yoganandkunche** [comment]
Defect passed QA
