### ISSUE TITLE
Answer with value '0' not stored

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#511]
### Expected behaviour
- Entering '0' for an answer is stored correctly and presented back to the user.
### Actual behaviour
- Entering '0' for an answer is not displayed on page refresh or on the summary screen.
### Steps to reproduce the behaviour
- Enter 0 for any numeric answer
- Navigate away from the page (save and continue)
- Navigate to the summary screen and see "no answer provided"
- Return to the page with the question on and observe the answer is empty
#### Browser

Chrome
#### Operating System

macOS Sierra
### Screenshot

<img width="367" alt="screen shot 2016-10-20 at 12 29 46" src="https://cloud.githubusercontent.com/assets/14041600/19558248/539a3d12-96c1-11e6-95df-e99694b9f479.png">
<img width="1060" alt="screen shot 2016-10-20 at 12 29 38" src="https://cloud.githubusercontent.com/assets/14041600/19558255/5b847150-96c1-11e6-8fb9-e6112ae85177.png">

**Comment by yoganandkunche** [comment]
Retest of defect Passed QA
