### ISSUE TITLE
Checkbox question with no answer blank on summary

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#514]
### Expected behaviour
- Not checking any checkboxes for a checkbox question shows as "No answer provided" on the summary screen.
### Actual behaviour
- The answer is blank on the summary screen.
### Steps to reproduce the behaviour
- Start 0_checkbox_other.json
- Don't select any answers to the checkbox question
- Navigate to the summary screen and observe that the answer is blank.
#### Browser

Chrome
#### Operating System

macOS Sierra
### Screenshot

<img width="472" alt="screen shot 2016-10-24 at 07 54 39" src="https://cloud.githubusercontent.com/assets/14041600/19641528/ffdfb5ce-99d8-11e6-949c-57574ee61727.png">

**Comment by yoganandkunche** [comment]
Defect Passed QA on branch
