### ISSUE TITLE
Other Checkbox/radio when selected and no answer provided does not throw error

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#516]
### Expected behaviour

When user selects an Checkbox or Radio button the text field must become mandatory and must throw error when when user does not enter a value
### Actual behaviour

Does not throw an error and on the summery page displays a 'Other' text entered and when edit is selected go back to the correct question but the test field is fill with 'Other' which the respondent did not enter.
### Steps to reproduce the behaviour
- Start 0_checkbox_other.json
- select Other and click save an continue 
- continue to summary screen and click 'edit' link 
#### Browser

All
### Screenshot

<img width="845" alt="screen shot 2016-10-24 at 11 16 24" src="https://cloud.githubusercontent.com/assets/21335236/19642066/60149660-99db-11e6-9381-1587d2687383.png">

**Comment by yoganandkunche** [comment]
following the discussion with @louise morris for a non mandatory question when user select 'other' option and does not provide answer then on the summary screen it must be displayed as 'Other - No answer provided'

**Comment by collisdigital** [comment]
Can we also add a test/schema that verifies when the question IS mandatory that it behaves as described (i.e. selecting Other requires an input).

**Comment by samiwel** [comment]
I think this is indirectly resolved by #521

**Comment by yoganandkunche** [comment]
Defect Passed QA on branch (this is fixed indirectly by PR #521)

**Comment by collisdigital** [comment]
Closing as fixed by #521
