### ISSUE TITLE
Get metadata can throw a RuntimeException during error handling causing stacktrace to be displayed in browser

### ISSUE THREAD

**Issue by benjefferies** [ONSdigital/eq-survey-runner#524]
### Expected behaviour

When an error occurs for a user with no metadata in the application we should see a error page with an error code
### Actual behaviour

When an error occurs for a user with no metadata in the application we should see a stacktrace
### Steps to reproduce the behaviour
- Start questionnaire
- Invalidate metadata (Unsure how to do this)
- Refresh page
### Technical information

We throw a runtime exception when there is no meta data here https://github.com/ONSdigital/eq-survey-runner/blob/master/app/data_model/questionnaire_store.py#L37
#### Browser

Chrome
53.0.2785.143
#### Operating System

OS X 10.11.6
### Screenshot

[RuntimeError_ ('No metadata for user %s', '5a4ede5dea984997fe13bf1138ebaff4addcf389e1d5d918bbec411b7db5a0aa') __ Werkzeug Debugger.pdf](https://github.com/ONSdigital/eq-survey-runner/files/553755/RuntimeError_.No.metadata.for.user.s.5a4ede5dea984997fe13bf1138ebaff4addcf389e1d5d918bbec411b7db5a0aa.__.Werkzeug.Debugger.pdf)

**Comment by collisdigital** [comment]
We believe this to be caused by having two different browsers/users open against the same session (ru_ref); we plan to prevent this scenario soon; will review this defect when that happens.

**Comment by jonnyshaw89** [comment]
Also we appear not to be catching exceptions properly and displaying 500 error page.

**Comment by ajmaddaford** [comment]
If we find there is no metadata then we should redirect to /session-expired. Card added to Trello https://trello.com/c/aMZBGZy2/1411-log-user-out-when-no-metadata
