### ISSUE TITLE
Is authenticator info logging too verbose?

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#532]
### Expected behaviour
- Authenticator only logs events that are useful operationally at INFO level
### Actual behaviour
- Authenticator logging unauthenticated users (is this useful?)
### Steps to reproduce the behaviour
- Check server logs
- see "Session does not have an authenticated token" logging every few seconds
### Technical information

Logging line is here: /app/authentication/authenticator.py:37
### Screenshot

<img width="871" alt="screen shot 2016-10-28 at 07 53 27" src="https://cloud.githubusercontent.com/assets/14041600/19797545/ac27012c-9ce3-11e6-8079-621a1127d91c.png">

**Comment by collisdigital** [comment]
For discussion, maybe this is useful afterall

**Comment by ajmaddaford** [comment]
This log message is output when the root '/' url is visited. This looks like it's because flask-login is initialised in `app/__init__.py` so happens for all requests regardless whether the user should be logged in or not.

**Comment by collisdigital** [comment]
Let's leave this issue open to review the flask-login usage for various routes then.

**Comment by collisdigital** [comment]
Is this still a problem, since we're now using structured logging as well?

**Comment by jonnyshaw89** [comment]
Logs less now
