### ISSUE TITLE
Validation error shows server error page when validation errors on page with skip condition question

### ISSUE THREAD

**Issue by benjefferies** [ONSdigital/eq-survey-runner#538]
### Expected behaviour
Validation errors relating to questions should appear at top of page

### Actual behaviour
Server error page is displayed

### Steps to reproduce the behaviour

1. Start star wars survey
1. Choose Leyoda, lightside
1. Complete page 2
1. Complete page 3 selecting `Awesome, I love them all` to question `What do you think of the prequel series?`
1. Try to `Save and continue` without selecting an answer

### Technical information
Error occurs at https://github.com/ONSdigital/eq-survey-runner/blob/master/app/questionnaire/questionnaire_manager.py#L322. The reason is because we cannot use __dict__ on a dict. Initially rule['when'] is an object but we use __dict__ to get the dict of the attributes but we also reassign rule['when'] to a dict therefore when we try to convert this to a dict using __dict__ the second time it fails as it is already a dict.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/15050019/19962809/4a48ef74-a1b1-11e6-816f-4d876ac711a4.png)

**Comment by collisdigital** [comment]
Fixed by #540

**Comment by yoganandkunche** [comment]
Defect passed retest in pre-prod
