### ISSUE TITLE
Update Python cryptography package to 1.5.3

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#544]
The python cryptography package has recently (2016-11-05) been updated to version 1.5.3 to fix a security issue. Although we don't use the HKDF functionality we should update to ensure we are running the most up to date (someone could introduce functionality that uses it at any time).

https://cryptography.io/en/latest/changelog/

**Comment by collisdigital** [comment]
Fixed by #546
