### ISSUE TITLE
Submitted at time missing on thank you page

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#551]
### Expected behaviour

When a survey is completed and the thank you page is displayed it should contain the text "Submitted on {{date}}"

### Actual behaviour

The text "Submitted on {{date}}" is not displayed on the summary screen

### Steps to reproduce the behaviour

- Complete any survey and submit
- View the thank you page

### Screenshot
![screen shot 2016-11-08 at 13 27 07](https://cloud.githubusercontent.com/assets/1754822/20100914/5fe576c2-a5b7-11e6-9e7f-48f8ae24426d.png)

**Comment by collisdigital** [comment]
Still occurring on pre-prod

**Comment by collisdigital** [comment]
Remove the supporting code that isn't needed anymore (date of submission).
