### ISSUE TITLE
Installation of Yarn causing intermittent Travis build failures

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#560]
### Expected behaviour

Travis installs Yarn successfully on every build

### Actual behaviour

Builds on Travis intermittently fail when requesting the PGP key for the Yarn repo:
`The command "sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3" failed and exited with 2 during`

See https://travis-ci.org/ONSdigital/eq-survey-runner/builds/175108630

**Comment by collisdigital** [comment]
#572 switched the yarn key to a more reliable server. If we haven't seen this issue recently I suggest it's closed.

**Comment by ajmaddaford** [comment]
👍
