### ISSUE TITLE
Changing radio option from Other fails

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#566]
### Expected behaviour
- After selecting Other and entering a value, changing to a different radio option updates my select.

### Actual behaviour
- After selecting Other and entering a value, any changes of radio selection are not stored unless the Other value is cleared manually.

### Steps to reproduce the behaviour
- Launch test_radio.json
- On "What is your favourite breakfast food" select "Other" and enter a value
- Select the "Eggs" radio option
- Save and continue
- See that the next question incorrectly shows the text entered into "Other" in the "Do you really want ____ for breakfast?"
- Click previous and see the wrong option selected

#### Browser
- Chrome

#### Operating System
- macOS Sierra

### Screenshot
- None

**Comment by yoganandkunche** [comment]
Defect passed re-test in pre-prod
