### ISSUE TITLE
'&' entered in Text is displayed as &amp;

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#573]
### Expected behaviour
Must navigate back to the Questions page displaying the correct answer 

### Actual behaviour

Navigating to the question but displays the answer as "Chicken &amp; Prawns" (PFA screenshot)

### Steps to reproduce the behaviour
Launch test_final_confirmation.json
Enter Chicken & Prawns for What is your favourite breakfast food
Click Save and Continue 
From the confirmation page click on [Change your Answers]
### Screenshot
<img width="869" alt="screen shot 2016-11-18 at 11 54 13" src="https://cloud.githubusercontent.com/assets/21335236/20431107/21f00360-ad90-11e6-9904-22bd7d985ae1.png">

**Comment by jcox-dev** [comment]
@yoganandkunche I'm unable to reproduce this. Is it still an issue?
