### ISSUE TITLE
Numeric inputs do not invoke numeric keypad on mobile devices

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#594]
### Expected behaviour

- On mobile devices, a numeric input should automatically use the numeric keyboard
### Actual behaviour

- Alphanumeric keyboard is used

### Steps to reproduce the behaviour

- Navigate to any MCI survey
- Navigate to first question containing numeric entry
- Confirm numeric keyboard is not invoked

#### Browser

Mobile Safari

#### Operating System

iPhone iOS 10

### Screenshot

![image](https://cloud.githubusercontent.com/assets/930398/20704364/dec646dc-b616-11e6-8c2d-10dcb25ac195.png)

**Comment by yoganandkunche** [comment]
Defect passed QA in preprod
