### ISSUE TITLE
Non mandatory other check box when a space is entered display on summary is not correct

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#596]
### Expected behaviour
Must display as No answer Provided

### Actual behaviour
Displays a bullet point and a blank (PFA)

### Steps to reproduce the behaviour
Launch Test_Checkbox
Select values for Mandatory checkbox 
navigate to non-mandatory checkbox 
Select Other and hit space and submit
Navigate to Summary screen

#### Browser
All Browsers

#### Operating System
All
### Screenshot
<img width="1158" alt="screen shot 2016-11-30 at 09 27 09" src="https://cloud.githubusercontent.com/assets/21335236/20746962/0b21070c-b6e0-11e6-9eff-50262c4c0904.png">

**Comment by iwootten** [comment]
I think this is already fixed in https://github.com/ONSdigital/eq-survey-runner/pull/583

**Comment by LJBabbage** [comment]
I think Yogi is referring to non-mandatory other value options

**Comment by iwootten** [comment]
I was referring to both mandatory and non-mandatory on the PR?

**Comment by yoganandkunche** [comment]
@iwootten: Upon retest of Defect #583 this issue is raised ( it is working fine with Mandatory other checkbox, but not for non mandatory other checkbox)

**Comment by collisdigital** [comment]
It is now fixed in pre-prod after the latest fix for Checkbox/Radio Other fields.
