### ISSUE TITLE
Census: Answering 'Yes' to Are you a schoolchild or student in full-time education? gives error 500

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#601]
### Expected behaviour

Term-time-location screen location screen must be displayed

### Actual behaviour
Giving an error '500"

### Steps to reproduce the behaviour
Please run the selenium script using the .js file attached 

yarn run test_functional -- --spec=census/issues/fulltime-education-question

Navigate to Question: Are you a schoolchild or student in full-time education?
Select Yes and click save and continue

### Screenshot
[census-issues.spec.js.zip](https://github.com/ONSdigital/eq-survey-runner/files/622232/census-issues.spec.js.zip)

**Comment by yoganandkunche** [comment]
Defect passed retest on branch

**Comment by jonnyshaw89** [comment]
Fixed by https://github.com/ONSdigital/eq-survey-runner/pull/608
