### ISSUE TITLE
Census: Selecting bottom 2 checkboxs for What is your country of birth? Gives error 500

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#602]
### Expected behaviour
Must display arrive in UK screen

### Actual behaviour
Displaying an error 500 screen

### Steps to reproduce the behaviour

Please run the selenium script using the .js file attached

yarn run test_functional -- --spec=census/issues/arrive-in-uk-question

Navigate to Question: What is your country of birth?
Select Yes and click save and continue

#### Browser
All Browsers
#### Operating System
All OS
### Screenshot
[census-issues.spec.js.zip](https://github.com/ONSdigital/eq-survey-runner/files/622339/census-issues.spec.js.zip)

**Comment by yoganandkunche** [comment]
Defect passed retest on branch

**Comment by jonnyshaw89** [comment]
Fixed by https://github.com/ONSdigital/eq-survey-runner/pull/608
