### ISSUE TITLE
Individual date question layout is wrong

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#604]
### Expected behaviour

An individual date question should be laid out with fields inline.

### Actual behaviour

Date question fields are stacked in certain cases.

### Steps to reproduce the behaviour

1. Start `census_individual` schema.
2. Complete questionnaire up to "3. What is your date of birth?" question.
3. Confirm field is laid out as screenshot below.

### Screenshot

<img width="309" alt="screenshot 2016-12-01 09 48 14" src="https://cloud.githubusercontent.com/assets/930398/20789136/50189520-b7ab-11e6-8a3f-ba1615306d1f.png">

**Comment by collisdigital** [comment]
This is now fixed.
