### ISSUE TITLE
Confirmation page uses incorrect base template

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#605]
### Expected behaviour

All pages in a user journey through a questionnaire should use a consistent theme (eg. Census).

### Actual behaviour

Confirmation page is not using theme'd template and subsequently appears malformed.

### Steps to reproduce the behaviour

1. Complete `census_individual` questionnaire.
2. Verify "confirmation" page has a malformed header as per screenshot.

### Screenshot

<img width="1063" alt="screenshot 2016-12-01 10 34 45" src="https://cloud.githubusercontent.com/assets/930398/20790931/8bcb34e0-b7b2-11e6-9b82-21ce5031a1f4.png">

**Comment by collisdigital** [comment]
This appears to be resolved in pre-prod, closing.
