### ISSUE TITLE
Question guidance not rendering properly on household composition after adding another person

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#607]
### Expected behaviour
After clicking 'Add another person' on the household composition screen the question guidance should still render properly

### Actual behaviour
Question guidance not rendering properly

### Steps to reproduce the behaviour
- Navigate to the household composition screen
- Click 'Add another person' 

#### Browser
Chrome

#### Operating System
OSX Sierra

### Screenshot
<img width="735" alt="screen shot 2016-12-01 at 11 47 54" src="https://cloud.githubusercontent.com/assets/1754822/20792963/8da83326-b7bc-11e6-90d7-1015010c0ad7.png">

**Comment by collisdigital** [comment]
This appears to be resolved on pre-prod; closing.
