### ISSUE TITLE
Census: The name piping on personal details screen is not according to the spec

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#616]
### Expected behaviour
Must display the the Name of the person under the Title: The following questions are for: (Please Find Attached)

### Actual behaviour
Name is not displayed under the Title: The following questions are for: (Please Find Attached)

### Steps to reproduce the behaviour

Launch Census Schema
Navigate to the Personal Details screen (Any Path)

#### Browser
All
#### Operating System
All
### Screenshot
![issue](https://cloud.githubusercontent.com/assets/21335236/20839608/2ed0c446-b8a5-11e6-84b1-879c7da542bb.png)

<img width="754" alt="screen shot 2016-12-02 at 15 26 03" src="https://cloud.githubusercontent.com/assets/21335236/20839630/398f90ec-b8a5-11e6-981f-7445fedcd277.png">

**Comment by samiwel** [comment]
@yoganandkunche Can you confirm if the group title should contain First and Last names (i.e. John Doe) and the descriptive test should include middle names if they exist (i.e. John James Doe). It's not clear from the spec, but that's what it looks like in you're issue screen shot. What are the requirements?

**Comment by yoganandkunche** [comment]
@samiwel Checked with Jenny and she thinks that it should match the spec file.. I can always check with @Louise Morries when she is in tomorrow and get back to you on this.

**Comment by samiwel** [comment]
Okay, once we have final confirmation from Louise I'll deliver the fix. I think it should be easy to resolve based on my testing so far.

**Comment by yoganandkunche** [comment]
@samiwel Checked with louiseM and she confirmed that it must be exactly as it is on the spec file. 
"Title should contain First and Last names (i.e. John Doe) and the descriptive test should include middle names if they exist (i.e. John James Doe)

**Comment by samiwel** [comment]
@yoganandkunche I believe this is fixed by PR #613 . There is some front-end work required to tidy up the solution. But if you want to test there, feel free.

**Comment by yoganandkunche** [comment]
Defect passed retest
