### ISSUE TITLE
Census: Individual section Navigation is wrong when no option is selected for 5. Do you stay at another address for more than 30 days a year?

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#663]
### Expected behaviour
Must take the user to Question 7

### Actual behaviour
Application is navigating to question 6 which is not correct.

### Steps to reproduce the behaviour
Launch Census Schema
Navigate to Individual section
Do not select any option for Q: 5. Do you stay at another address for more than 30 days a year?

**Comment by benjefferies** [comment]
This is also an issue for the census individual schema

**Comment by collisdigital** [comment]
Agreed with Census we won't do routing based on dates, additional guidance added to cover this change to always show this question.
