### ISSUE TITLE
This security message should probably be above the button as screen readers won't see this at all prior to reaching the primary action on the page

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#669]
[https://www.bugherd.com/projects/110463/tasks/5](https://www.bugherd.com/projects/110463/tasks/5)

**Comment by collisdigital** [comment]
Presumably if you're really concerned about security you wouldn't start the survey anyway so would get to the message ? ;)

**Comment by collisdigital** [comment]
Closing this and adding card to the DAC backlog board for review and testing.

**Comment by collisdigital** [comment]
https://trello.com/c/x0fIb01G/27-this-security-message-should-probably-be-above-the-button-as-screen-readers-won-t-see-this-at-all-prior-to-reaching-the-primary-
