### ISSUE TITLE
Correct name not piped in, also should name be bolded?

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#675]
[https://www.bugherd.com/projects/110463/tasks/17](https://www.bugherd.com/projects/110463/tasks/17)

**Comment by collisdigital** [comment]
Can't see bugherd contents but suspect this is fixed by #683

**Comment by collisdigital** [comment]
Closing this, please re-open with detail in GitHub Issue if still a problem.
