### ISSUE TITLE
number inputs need maxlength set

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#676]
[https://www.bugherd.com/projects/110463/tasks/20](https://www.bugherd.com/projects/110463/tasks/20)

**Comment by collisdigital** [comment]
Backend range check validation is due in the new year (possibly tied with WTForms integration).

**Comment by hamishtaplin** [comment]
@collisdigital this can be enforced by using the `maxlength` attribute of an `input`. Makes sense to add as it will degrade gracefully anyway—just an enhancement for newer browsers.

**Comment by collisdigital** [comment]
What should the length be though and is it the same for all inputs?
