### ISSUE TITLE
Census_Household: No Edit link on relationship page when only two people are there in a household

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#697]
### Expected behaviour ###
Must have an edit link to edit the relationship when only two people are there in a household.

### Actual behaviour
No edit link is present to edit the relationship (Please find attached screenshot)
### Steps to reproduce the behaviour
Launch census_household survey
Add One extra person
Navigate to relationship screen
Select a relationship click save and continue
click previous
### Screenshot
<img width="797" alt="screen shot 2016-12-12 at 11 38 54" src="https://cloud.githubusercontent.com/assets/21335236/21098146/a87f15c4-c05f-11e6-9a98-244a333b63d0.png">

**Comment by collisdigital** [comment]
Shown to @hamishtaplin today.

**Comment by yoganandkunche** [comment]
Defect passed retest.
