### ISSUE TITLE
Answers are not bleached before being stored in answer_store

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#699]
### Expected behaviour
When i post malicious content to the application then this should be sanitised before being stored and displayed on subsequent pages.

### Actual behaviour
The malicious content is being stored in the answer-store and displayed on subsequent pages

### Steps to reproduce the behaviour
On the census_household.json In the persons name enter `<img src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png"/>`

**Comment by samiwel** [comment]
@jonnyshaw89 Just checked and it appears that at least some answers are being bleached before storing in the answer store. This happens during validation in schema. The `bleach.clean` call is what causes everything after the '<' when entering a household name to be lost (see #695). Not sure if there's a way of telling the clean method not so strip content, but rather encode the value?

**Comment by samiwel** [comment]
Looks promising... https://docs.python.org/3/library/html.html#html.escape The second argument allows escaping of quotation marks.

**Comment by collisdigital** [comment]
Closing this as we bleach values on input from widgets.
