### ISSUE TITLE
On the guidance padding increase the space between the link and response option to at least 1rem

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#702]
[https://www.bugherd.com/projects/110463/tasks/30](https://www.bugherd.com/projects/110463/tasks/30)

**Comment by will-madebymoon** [comment]
Here is an example where I've spaced the guidance by 1rem
<img width="1071" alt="screen shot 2016-12-13 at 11 44 05" src="https://cloud.githubusercontent.com/assets/8184622/21139242/cfb65da8-c129-11e6-8172-3e880344593d.png">

**Comment by collisdigital** [comment]
Fixed on pre-prod. Closing.
