### ISSUE TITLE
These fields appears to very small in width on the largest breakpoint

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#703]
[https://www.bugherd.com/projects/110463/tasks/31](https://www.bugherd.com/projects/110463/tasks/31)

**Comment by will-madebymoon** [comment]
<img width="971" alt="screen shot 2016-12-13 at 11 07 28" src="https://cloud.githubusercontent.com/assets/8184622/21138084/68cdf678-c124-11e6-89d1-e8dc6f99aff4.png">

On the largest breakpoint I've increased this to 20rem which matches the space allocated for radio fields and checkboxes.
