### ISSUE TITLE
There should be more padding between the response options

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#706]
[https://www.bugherd.com/projects/110463/tasks/32](https://www.bugherd.com/projects/110463/tasks/32)

**Comment by will-madebymoon** [comment]
<img width="965" alt="screen shot 2016-12-13 at 11 14 22" src="https://cloud.githubusercontent.com/assets/8184622/21138401/d19c8c72-c125-11e6-8707-ed6c6a289c20.png">

Increasing the margin to 1.5rem improved the spacing
