### ISSUE TITLE
Census_Household: On Question 5 Who live here? section additional guidance is displayed on screen instead of Show/Hide

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#709]
### Expected behaviour
Must display the Guidance within Show/Hide 

### Actual behaviour
Guidance is displayed on screen with out show/hide feature

### Steps to reproduce the behaviour
Launch Census Household schema
Navigate to question 5 under Who lives here section

### Screenshot
<img width="793" alt="screen shot 2016-12-13 at 10 49 40" src="https://cloud.githubusercontent.com/assets/21335236/21137596/27734658-c122-11e6-9816-089a4cca1943.png">

**Comment by collisdigital** [comment]
Covered by https://trello.com/c/Oc4yln5z/806-make-guidance-on-relationship-screen-show-hide

**Comment by yoganandkunche** [comment]
Defect passed retest following deployment on 20th Dec 2016
