### ISSUE TITLE
Add more margin to the last item in the highlighted guidance panel

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/eq-survey-runner#710]
<img width="735" alt="screen shot 2016-12-13 at 10 53 33" src="https://cloud.githubusercontent.com/assets/8184622/21137701/95efe17c-c122-11e6-93d2-ee2b28499488.png">

In the screenshot I've added 0.75rem

**Comment by collisdigital** [comment]
This is already fixed.
