### ISSUE TITLE
Census_Household_Sexual_ID(true): Is not displaying the Sexual_ID question in the survey

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#715]
### Expected behaviour
Must ask respondent the following question "Which of the following options best describes how you think of " while filling the questionnaire

### Actual behaviour
Not displaying 'Which of the following options best describes how you think of ' question for the respondent

### Steps to reproduce the behaviour
Launch Census Household schema
Navigate to ethnic group and answers the ethnic questions and click [Save and continue]

### Technical information

Claim details passed on from RH are as followes
{:collection_exercise_sid=>"0", :eq_id=>"census", :exp=>1481632766, :form_type=>"household", :iat=>1481629166, :language=>"en", :period_id=>"", :period_str=>"", :ref_p_start_date=>"2000-01-01", :ref_p_end_date=>"2000-01-01", :region_code=>"GB-ENG", :ru_name=>"", :ru_ref=>"1000000000002215", :return_by=>"2000-01-01", :tx_id=>"4962db4b-4392-4149-a56d-1be69acea202", :user_id=>"", :variant_flags=>{:sexual_identity=>true}}

**Comment by collisdigital** [comment]
Ian picking this up as part of sex id and age routing rules

**Comment by yoganandkunche** [comment]
Defect passed retest.
