### ISSUE TITLE
Cenus_Household: Additional interstitial page after completion of visitors section

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#721]
### Expected behaviour
Additional interstitial page following completions of visitors section which will help to get a green tick next to visitors section

**Note:** Following discussion with Lousie M, Louise agreed to the spec with the additional Interstitial page after visitors section with wordings.

Please find below is the updated spec file from Louise: **Page 87** (for the new interstitial page)

https://docs.google.com/presentation/d/1gQBIWtAJg5Z7mnbZwffUPBdlWPL4rtiaz42f-Fp_vsM/edit#slide=id.g1a0d77a79c_0_53

### Actual behaviour
Upon completion of visitors section the Navigation must display a green tick mark next to visitors section.

### Steps to reproduce the behaviour
Launch Census Household schema
Navigate to Visitors section and complete the sections

**Comment by samiwel** [comment]
@LJBabbage Is this being looked at in #628?

**Comment by LJBabbage** [comment]
Yep I am, good catch

**Comment by yoganandkunche** [comment]
This defect was fixed as part of another PR.

Retest proves it works as expected
