### ISSUE TITLE
Show further guidance on household composition is in wrong place

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#737]
### Expected behaviour
Show further guidance shown below Add Person button

### Actual behaviour
Show further guidance shown below each person's last name.

### Steps to reproduce the behaviour
- navigate to HH composition screen.

#### Browser
Chrome

#### Operating System
macOS

### Screenshot
![image](https://cloud.githubusercontent.com/assets/14041600/21225340/45d00954-c2c8-11e6-9910-8abc2b511a78.png)

**Comment by yoganandkunche** [comment]
Defect passed retest following deployment on 20th Dec 2016
