### ISSUE TITLE
Some text in the further guidance gets clipped at container boundary

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-survey-runner#741]
### Expected behaviour
All the guidance text is visible.

### Actual behaviour
Some text gets clipped. I noticed this on a few questions.

### Steps to reproduce the behaviour
Navigate through the household survey.
Expand the further guidance sections.

### Technical information
Page zoom was set at 100% and window width was wide enough to display content and the new navigation.

#### Browser
Chrome

#### Operating System
N/A

### Screenshot
![image](https://cloud.githubusercontent.com/assets/4097796/21230432/dc131abe-c2dc-11e6-9652-e7d939b60179.png)

**Comment by hamishtaplin** [comment]
I already fixed this in another branch. Here's how that guidance currently looks on master (not the alignment of the line with the chevron above)

<img width="635" alt="screenshot 2016-12-17 18 46 52" src="https://cloud.githubusercontent.com/assets/930398/21289005/4cddec80-c489-11e6-9b8d-9a71de0c2195.png">
