### ISSUE TITLE
Census_Household: Show further guidance on add another person not working

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#746]
### Expected behaviour
Must allow user to expand the Show further guidance for person 2 onwards or remove that as we already have one.

### Actual behaviour
When a additional person is added does not allow user to expand the guidance

### Steps to reproduce the behaviour
Launch Census_Household survey
Navigate to Question 2 under who lives here 
Click add another person
Click on 'Show further guidance' for person 2

**Comment by collisdigital** [comment]
Actually this is the issue: https://github.com/ONSdigital/eq-survey-runner/issues/737

Can we close this one?

**Comment by yoganandkunche** [comment]
Sure
