### ISSUE TITLE
'Is this everyone for whom this is their permanent or family home?' question preselects answer

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#749]
### Expected behaviour

Not all answers should retain their selected response when returned to. 

On the question 'Is this everyone for whom this is their permanent or family home?', upon answering 'No, I need to add another person', subsequently adding another person and then navigating back to the question, 'No...' answer should be not selected.

### Actual behaviour

The 'No, I need to add another person' answer is preselected—this is the least likely option that a user would select here and clicking 'Save and continue' without changing their 'answer' takes them backwards.

### Steps to reproduce the behaviour

- start 'household_composition' questionnaire
- complete up to adding people, add one or more
- progress to 'Is this everyone for whom...' question
- select 'No..' option
- save and continue
- 'No...' option is already selected

### Technical information

N/A

### Screenshot

![screenshot 2016-12-16 12 13 05](https://cloud.githubusercontent.com/assets/930398/21262399/0f7042cc-c389-11e6-8037-ebccb942b448.png)

**Comment by collisdigital** [comment]
Interesting, I thought we did remove this answer; you could argue that this screen should be skipped if you already went back (i.e. assume answer is Yes and move on) - not suggesting we do that now.

**Comment by samiwel** [comment]
Seems like the logic is identifying groups to delete. This particular block is not inside one of the repeating groups so the answer is not deleted.
