### ISSUE TITLE
'Previous' link missing on household relationship question

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#751]
### Expected behaviour

On the question 'How are members of this household related to each other?' there should be 'previous' links present.

### Actual behaviour

No 'previous' links are present

### Steps to reproduce the behaviour

- select `household_relationship` survey.
- proceed to 'How are members of this household related to each other?' question.
- no 'previous' links

### Technical information

n/a

### Screenshot

![screenshot 2016-12-16 13 04 02](https://cloud.githubusercontent.com/assets/930398/21263764/69d1f38a-c390-11e6-8c12-15c49e91c5c7.png)

**Comment by hamishtaplin** [comment]
Had a look at this and the issue is that `previous_location` is `None` in the [template](https://github.com/ONSdigital/eq-survey-runner/blob/master/app/templates/layouts/_base.html#L49).

**Comment by iwootten** [comment]
This is because we hide the previous location for the first block in each group (due to the confusion for sidebar navigation) and the relationship question exists in its own group.
