### ISSUE TITLE
Census_Household - Previous link not existing on question number 5. How are members of this household related to each other?

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#755]
Expected
Previous link should exist

Actual
Previous link does not exist

Steps to reproduce
1. Enter the unique access code in respondent home page
2. Click on Continue button
3. Questionnaire page is displayed
4. Navigate to question '5. How are members of this household related to each other?'
5. Verify the previous link exists

Browser

Chrome

Operating System

Windows

Screenshot

No

**Comment by collisdigital** [comment]
Duplicate of https://github.com/ONSdigital/eq-survey-runner/issues/751 ?

**Comment by yoganandkunche** [comment]
Yes looks like it will close this now
