### ISSUE TITLE
Census_Household: error pre-exists for newly added person

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#758]
Expected
Must not display error message for newly added person

Actual
Displays error message for newly added person

Steps to reproduce
Launch Census_Household survey
Navigate to Q.2 List the names of everyone who lives here page
click save and continue with out entering first name
Displays error message
Enter a valid name 
and click add another person

Browser

Chrome

Operating System

Windows

Screenshot

No

**Comment by collisdigital** [comment]
This is a low priority issue
