### ISSUE TITLE
Some characters in Welsh are not rendered in the standard font

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#769]
### Expected behaviour
All welsh text should render correctly using the standard EQ font.

### Actual behaviour
Characters like ŷ are rendered in a different font and appear bold.

### Steps to reproduce the behaviour
Load the Welsh language version of either the Census Household or Individual survey and navigate to a question containing a ŷ character.

#### Browser
Safari

#### Operating System
OSX

### Screenshot
![](https://cloud.githubusercontent.com/assets/7594012/21316840/8082301a-c5fa-11e6-975c-71543e52b519.png)

**Comment by bennpearson** [comment]
Note: Welsh characters present for the font weights 400 and 800
