### ISSUE TITLE
Census_Welsh Languag: Error message Title displayed in English

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#783]
### Issue
Not sure if we will translate the error title to Welsh or not... we can discuss

### Screenshot
<img width="736" alt="screen shot 2016-12-20 at 15 10 45" src="https://cloud.githubusercontent.com/assets/21335236/21355660/c59b437c-c6c6-11e6-86ec-60f68c2cecc5.png">

**Comment by collisdigital** [comment]
We don't, this is covered by the system content translation story which wasn't in scope; so isn't a defect. Closing.
