### ISSUE TITLE
Census - Welsh - Question 5a - Question Text formatting issue

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#787]
### Expected behaviour
Question must be displayed correctly

### Actual behaviour
Question text is not displayed correctly

### Steps to reproduce the behaviour
Enter the unique access code in respondent home page
Click on Continue button
Questionnaire page is displayed
Navigate to question '5a. Rhowch fanylion y cyfeiriad arall yn y Deyrnas Unedig lle rydych yn aros am fwy na 30 diwrnod'

Note: Works fine for English Language.

#### Browser
IE 11
### Screenshot
![image1](https://cloud.githubusercontent.com/assets/17926778/21357595/a49b25e6-c6cd-11e6-8fe3-8440bfe0a1f4.PNG)

**Comment by hamishtaplin** [comment]
@yoganandkunche Can you make sure you log the browser/OS when raising bugs as this could be browser-specific.

Also, it's not very clear how to 'Navigate to question 5a', is there some routing happening?

**Comment by yoganandkunche** [comment]
@hamishtaplin : Sure.. I have updated the browser information in the defect (IE11)
To recreate the defect navigate to question 5 while answers individual questions and select option 2 and click save and continue
