### ISSUE TITLE
CSS/JS assets are not minified

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#833]
### Expected behaviour

CSS and JS files should be minified in pre-prod/prod

### Actual behaviour

Assets are not minified

### Steps to reproduce the behaviour

- Load page in any browser
- Confirm CSS/JS assets do not use the minified versions via the filename (eg. should be .min.js)

#### Browser

All

### Screenshot

<img width="1020" alt="screenshot 2017-01-11 11 18 19" src="https://cloud.githubusercontent.com/assets/930398/21846639/f4a5aa1a-d7ef-11e6-9df8-634bd3f52c36.png">

**Comment by adoublebarrel** [comment]
The good news is that in terms of code functionality we seem to have everything we need.

The bad news is that the minification build step isn't in place so if we turned on serving the minified versions right now things would go bang.

### Steps To Fix

1. Enable minification for pre-prod and prod builds (and dev?)
1. Switch the EQ_MINIMIZE_ASSETS env var to True in Jenkins for pre-prod and prod 

Source maps is all setup so we could use the minified assets in dev, @ajmaddaford is likely to check if that works for @hamishtaplin
