### ISSUE TITLE
404 error when starting 0215 survey

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/eq-survey-runner#843]
### Expected behaviour
When starting a 0215 survey the introduction page should be displayed

### Actual behaviour
A 404 error page is displayed

### Steps to reproduce the behaviour
Start the 0215 survey

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1754822/21983412/18d649e2-dbe9-11e6-8c5e-b22ecf428082.png)

**Comment by ajmaddaford** [comment]
The issue has been identified as duplicate id's in the 0215 JSON - `number-male-employees-under-30-hours` is used for a question and answer

**Comment by yoganandkunche** [comment]
Defect passed QA in Pre-prod
