### ISSUE TITLE
Highlight style of emphasis should be limited to question title

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#863]
### Expected behaviour

- The "highlight" style applied to `em` should only be used in question title, with bold being used elsewhere.

### Actual behaviour

- Highlight style is used throughout

### Steps to reproduce the behaviour

- open UKIS `1_0001.json`
- highlight is used throughout in text that is not question title

### Screenshot

<img width="1049" alt="screenshot 2017-01-23 09 51 33" src="https://cloud.githubusercontent.com/assets/930398/22201775/047ab252-e15d-11e6-82c0-eb8d6cbcda0c.png">

**Comment by collisdigital** [comment]
Discussed with Emma and Bethan; highlighting will only be enabled for question text and in all other areas will use **bold** text.
