### ISSUE TITLE
UKIS: Northern Ireland Schema is not launched correctly

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#865]
### Expected behaviour
Launching a GB-Eng Schema instead

Following the investigation RRM is passing **GB-NIR** as the Region Code where as eQ is expecting this code to be **GB-NI**

### Actual behaviour

Must navigate to UKIS Northern Ireland landing page with the correct Logo

### Steps to reproduce the behaviour
Launch an UKIS (Northern Ireland) Survey from RRM
Must navigate to UKIS Northern Ireland landing page with the correct Logo

**Comment by collisdigital** [comment]
https://en.wikipedia.org/wiki/ISO_3166-2:GB lists Northern Ireland as GB-NIR as specified by RRM Classic.

**Comment by samiwel** [comment]
Are RRM using the wrong standard? The ons-schema-definitions repository lists ISO 3166-1 alpha-2 for the region_code token? See https://github.com/ONSdigital/ons-schema-definitions/blob/master/docs/rm-eq.rst
