### ISSUE TITLE
Census: Makes changes on Add another person screen and clicking [Save and come back later causing issues

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#886]
**Issue 1:**

### Expected behaviour
[Save and Come] back later must behave as Save on that screen and must **wipe the data** already entered.
### Actual behaviour
Data is not wiped and newly added person is listed in navigation 

### Steps to reproduce the behaviour
Launch Census_Household schema
Add 2 people to the household and enter visitors and continue to the relationships screen
Enter household and accommodation details
Enter some details for the 1st person 
and navigate back to add person screen
Click add another person and add details  and click [Save and come back later]

Launch the same survey again

**Issue 2:**

### Expected behaviour
[Save and Come] back later must behave as Save on that screen and must **wipe the data** already entered.
### Actual behaviour
Data is not wiped and Details of the 3rd person are copied to the person 2 please find the attached screenshot 

### Steps to reproduce the behaviour
Launch Census_Household schema
Add 3 people to the household and enter visitors and continue to the relationships screen
Enter household and accommodation details
Enter some details for the 1st person 
and navigate back to add person screen
Remove person 2 and click save and come back later.

Launch the same survey again

### Screenshot
<img width="1139" alt="screen shot 2017-01-27 at 15 50 15" src="https://cloud.githubusercontent.com/assets/21335236/22377140/9f7d6c92-e4a8-11e6-80a0-8cc4168cf483.png">

**Comment by LJBabbage** [comment]
Needs retesting as #901 should fix this

**Comment by yoganandkunche** [comment]
Defect Retested on Master and works as expected.
