### ISSUE TITLE
Census: Household Composition: JS Disabled Cannot Remove Person

### ISSUE THREAD

**Issue by collisdigital** [ONSdigital/eq-survey-runner#889]
### Expected behaviour
When JS is disabled I can still remove people

### Actual behaviour
When JS is disable I cannot remove a person

### Steps to reproduce the behaviour
- Disable JS (e.g. Chrome->Settings->Advanced->Content Settings->Do not allow any site to run JS)
- Navigate to Household Composition
- Add 3 people
- Try and remove Person 2
- Observe the link (Remove) does nothing

#### Browser
Chrome or Lynx (Terminal)

#### Operating System
Windows / macOS Sierra

### Screenshot
![image](https://cloud.githubusercontent.com/assets/14041600/22382664/8271108e-e4be-11e6-88a9-b70a80b3413d.png)

**Comment by collisdigital** [comment]
Could be related to https://github.com/ONSdigital/eq-survey-runner/issues/888

**Comment by collisdigital** [comment]
Likely to be caused by https://github.com/ONSdigital/eq-survey-runner/pull/874

**Comment by samiwel** [comment]
Hmm, yeah it's no longer a submit button so won't submit to the household composition endpoint in `questionnaire.py`. Perhaps the ENTER key needs to be handled by JS after all, or we need to re-think the solution for the Remove person link.

Interesting this wasn't caught by selenium test, perhaps there needs to be another selenium test with JS turned off. Would have caught this regression.
