### ISSUE TITLE
Pre-Prod: All the surveys when launched intermittently give error 500

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#895]
### Expected behaviour
Must not get an error 500

### Actual behaviour
Intermittently giving error 500

### Steps to reproduce the behaviour
Launch any eQ survey 

### Screenshot
<img width="722" alt="screen shot 2017-01-30 at 11 20 44" src="https://cloud.githubusercontent.com/assets/21335236/22421248/2b4aaabe-e6de-11e6-8103-b9a4dbf9998f.png">

**Comment by ajmaddaford** [comment]
Issue has been identified as one ec2 instance with the recurring error `extern "Python": function Cryptography_pem_password_cb() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.`. This looks like it's related to #870.
