### ISSUE TITLE
Non Mandatory Date field does not work as expected

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#922]
### Expected behaviour
Must throw an validation error when only month/year or month & year selected as the date entered is invalid. 

### Actual behaviour
Does not throw any validation errors

### Steps to reproduce the behaviour
Launch Census Individual/Household survey
navigate to date of birth field

- 1 Select only month and click [Save and continue]
 or
- 2 Select Month and Year click [Save and continue]

**Comment by iwootten** [comment]
Fixed in #928
