### ISSUE TITLE
Other text field retains data even the user changes the option

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#923]
### Expected behaviour
Must wipe the data entered in other text field before when user changes the option.

### Actual behaviour
Retains previously entered text.

### Steps to reproduce the behaviour
Launch any survey which has an other text field option
select other and enter data and click save and continue
navigate back using previous change the option and click save and continue
navigate back and select the other option again

**Comment by samiwel** [comment]
@yoganandkunche Do you have a selenium test for this defect already? If not I will write one, then look at fixing it.
