### ISSUE TITLE
Non mandatory date field does not allow to 'select month' value from the drop down  

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#930]
### Expected behaviour
Must allow to select 'select month' if it is a non mandatory date field

### Actual behaviour
'Select month' value is greyed out for an non mandatory date field

### Steps to reproduce the behaviour
Launch any survey which has a non mandatory date entry field
select a month from the drop down
and then try to select the 'select month' from the drop down

### Screenshot
<img width="664" alt="screen shot 2017-02-09 at 10 57 19" src="https://cloud.githubusercontent.com/assets/21335236/22780418/8f2670c4-eeb6-11e6-8344-be5357504bb2.png">

**Comment by iwootten** [comment]
Fixed in #928
