### ISSUE TITLE
Displays invalid validation error message on the date field.

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#931]
### Expected behaviour
Must not display error when the date is 28/feb/2019 which is within the range.

### Actual behaviour
Displaying wrong error message for a incorrect field (Please find attached) 

### Steps to reproduce the behaviour
Launch a survey with date range (ex: 0102)
Enter 28/Feb/2019 for From
Enter 31/Sept/2020 for To
and click save and continue.

### Additional information
Tested in Pre-prod and it fails (something caused from WTForms). Work fine in Prod
#### Browser
Chrome
### Screenshot
<img width="822" alt="screen shot 2017-02-09 at 11 01 39" src="https://cloud.githubusercontent.com/assets/21335236/22780704/855a0b22-eeb7-11e6-8327-e7aaa873a6c8.png">

**Comment by samiwel** [comment]
@yoganandkunche Can you please re-test this against master. I cannot reproduce the issue.

**Comment by samiwel** [comment]
Discussed with @yoganandkunche, expected behaviour: there shouldn't be an error message around the Period from date, only the Period to date.
