### ISSUE TITLE
Summary page bottom border cut off for Other answer

### ISSUE THREAD

**Issue by benjefferies** [ONSdigital/eq-survey-runner#965]
### Expected behaviour
Summary bottom border should be visible.

### Actual behaviour
Summary bottom border is hidden.

### Steps to reproduce the behaviour
1. Go to https://preprod-surveys.eq.ons.digital/dev
1. Start test_checkbox.json
1. Complete questionnaire
1. Observe missing bottom border on summary

#### Browser
Google Chrome Version 56.0.2924.87 (64-bit)

#### Operating System
10.12.3 (16D32)

### Screenshot
![image](https://cloud.githubusercontent.com/assets/15050019/23121148/2d78cfee-f757-11e6-8fec-e6841c2ed8fa.png)

**Comment by bennpearson** [comment]
`overflow: visible` on `.summary__items` possible fix

**Comment by yoganandkunche** [comment]
We need the question numbers displayed on the summary page.
