### ISSUE TITLE
Summary screen when using 'Other' question type

### ISSUE THREAD

**Issue by LJBabbage** [ONSdigital/eq-survey-runner#966]
### Expected behaviour
The summary screen should show 'please specify other' if an other value is selected/written in. 
### Actual behaviour
At the moment it shows it regardless, whether it has a value or not
![image](https://cloud.githubusercontent.com/assets/14179817/23122432/160b5a16-f75c-11e6-9a16-b144a97658cf.png)

### Steps to reproduce the behaviour
Using test_checkboxes.json. Pick a value bar 'Other' for the first question (Mandatory) and select 'Other' in the second question ( Non-Mandatory) but write no value in it

**Comment by benjefferies** [comment]
Already raised under https://github.com/ONSdigital/eq-survey-runner/issues/965

**Comment by collisdigital** [comment]
There's also other display issues here, blank rows above the answers etc etc.

**Comment by collisdigital** [comment]
Now fixed
