### ISSUE TITLE
Accessibility: Census/UKIS once a page is submitted the tab sequence is not as expected  

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#974]
### Expected behaviour

The tab sequence must go to skip content

### Actual behaviour

Skipping all the links and going straight to content.

### Steps to reproduce the behaviour
Launch Census/UKIS survey
Navigate to 1st question
Hit tab and click skip to content
Answer the question and click [save and continue]
Hit tab again

**Comment by iwootten** [comment]
@yoganandkunche This description isn't clear. Can you elaborate on what the expected/actual behaviour is please?

**Comment by armstrongb** [comment]
@yoganandkunche can you let me know if this issue is still valid?
