### ISSUE TITLE
Census: missing previous link on ' you have successfully completed the ‘Who lives here?’ section' page

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#981]
### Expected behaviour
<previous> link must be available to navigate back to the previous question according to spec

### Actual behaviour
<previous> link not available please find the attached screen shot.

### Steps to reproduce the behaviour
Launch Census Household survey
Complete Who lives here section.

### Screenshot
<img width="1149" alt="screen shot 2017-02-23 at 09 29 49" src="https://cloud.githubusercontent.com/assets/21335236/23253053/091232ac-f9ab-11e6-983d-e16b84f20e69.png">

**Comment by collisdigital** [comment]
Won't fix, part of the wider respondent journey and changes we'll be implementing
