### ISSUE TITLE
Session timeout unexpected behaviour when browser tab is inactive

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#988]
### Expected behaviour

- Session timeout should behave the same when the browser tab is inactive as it does when the browser tab is active

### Actual behaviour

- If the session timeout expires while the browser tab is inactive, the timer does not expire in the background

### Steps to reproduce the behaviour

- Open any survey
- Open a new tab
- Wait for timeout to expire
- Switch back to tab

**Comment by hamishtaplin** [comment]
I'm unable to recreate this. Session expiration will continue in the background as expected and forward to appropriate page when the session expires.

**Comment by nealedj** [comment]
Closing in favour of #1150
