### ISSUE TITLE
S-2 1st Page Date format display

### ISSUE THREAD

**Issue by stevevic** [ONSdigital/eq-survey-runner#99]
The period date is to be displayed as sent through from RM (use field periodstr which should be a string e.g. April 2016)

**Comment by weapdiv-david** [comment]
The period string is being displayed exactly as sent from the Repsondent Manager...

https://github.com/ONSdigital/eq-survey-runner/blob/master/app/main/views/cover_page.py#L28

Is this something we need to take up with them?

**Comment by stevevic** [comment]
Based on code presented - Ok to close.  Thank you
