### ISSUE TITLE
Timeout not saving the answers 

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/eq-survey-runner#991]
### Expected behaviour
When a survey times out all the answers entered till that point must be saved. 

### Actual behaviour
No answers are saved when the session times out 

### Steps to reproduce the behaviour
Launch any survey in pre-prod
answer 2 questions and on the 3rd question allow the session to time out 
launch the same survey with the same JWT details 

#### Browser
Chrome

**Comment by collisdigital** [comment]
Fixed by #993
